"""CLI entry point for The Weekly Thing audio pipeline."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml
from dotenv import load_dotenv

from manifest import hash_text, now_iso, read_manifest, script_path, write_manifest
from script import body_to_audio_script
from synthesize import AUDIO_VOICE, chunk_plan, synthesize_mp3
from upload import object_exists, public_url, upload_audio

LEGACY_BRIEFLY_FIELDS = ("briefly_synthesis_hash", "briefly_synthesis_text", "briefly_syntheses")

REPO = Path(__file__).resolve().parents[2]
ARCHIVE_DIR = REPO / "site" / "archive"
TMP_DIR = REPO / "tmp"
GENERATED_NOTICE_RE = re.compile(
    r"^<!-- Generated by (?:scripts/content|pipeline/content/content)\.py from data/buttondown; do not edit directly\. -->\r?\n"
)

sys.stdout.reconfigure(line_buffering=True)
load_dotenv(REPO / ".env")


def issue_sort_key(value: Any) -> tuple[int, str]:
    text = str(value)
    match = re.match(r"(\d+)", text)
    if not match:
        return (10**9, text)
    return (int(match.group(1)), text)


def parse_archive_file(path: Path) -> tuple[dict[str, Any], str]:
    raw = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.+?)\n---\n(.*)", raw, re.DOTALL)
    if not match:
        raise RuntimeError(f"{path} is missing YAML front matter")
    frontmatter = yaml.safe_load(match.group(1)) or {}
    body = GENERATED_NOTICE_RE.sub("", match.group(2)).strip()
    return frontmatter, body


def archive_path(issue: str) -> Path:
    path = ARCHIVE_DIR / f"{issue}.md"
    if not path.exists():
        raise RuntimeError(f"Archive issue not found: {path}")
    return path


def all_archive_issues() -> list[str]:
    issues = [
        path.stem
        for path in ARCHIVE_DIR.glob("*.md")
        if path.stem not in {"archive", "redirects"}
    ]
    return sorted(issues, key=issue_sort_key)


def latest_issue() -> str:
    latest: tuple[str, str] | None = None
    for issue in all_archive_issues():
        frontmatter, _ = parse_archive_file(archive_path(issue))
        publish_date = str(frontmatter.get("publish_date", ""))
        if latest is None or publish_date > latest[1]:
            latest = (issue, publish_date)
    if latest is None:
        raise RuntimeError("No archive issues found.")
    return latest[0]


def selected_issues(args: argparse.Namespace) -> list[str]:
    if args.issue:
        return [str(args.issue)]
    if args.all:
        return all_archive_issues()
    return [latest_issue()]


def render_script(issue: str) -> str:
    frontmatter, body = parse_archive_file(archive_path(issue))
    return body_to_audio_script(body, frontmatter)


def scrub_legacy_briefly_fields(manifest: dict[str, dict[str, Any]]) -> bool:
    changed = False
    for entry in manifest.values():
        for field in LEGACY_BRIEFLY_FIELDS:
            if field in entry:
                entry.pop(field, None)
                changed = True
    return changed


def is_up_to_date(issue: str, script_hash: str, manifest_entry: dict[str, Any]) -> bool:
    return (
        manifest_entry.get("audio_script_hash") == script_hash
        and manifest_entry.get("audio_voice") == AUDIO_VOICE
        and object_exists(issue)
    )


def write_dry_run(issue: str, text: str) -> None:
    TMP_DIR.mkdir(parents=True, exist_ok=True)
    path = TMP_DIR / f"audio-script-{issue}.txt"
    path.write_text(text, encoding="utf-8")
    print(f"Dry run wrote {path.relative_to(REPO)}")
    print("Chunk plan:")
    for chunk in chunk_plan(text):
        print(f"  chunk {chunk['index']}: {chunk['characters']} characters")


def build_issue(issue: str, manifest: dict[str, dict[str, Any]], dry_run: bool, force: bool) -> bool:
    entry = manifest.get(issue, {})
    text = render_script(issue)
    script_hash = hash_text(text)

    if dry_run:
        write_dry_run(issue, text)
        return False

    existing_script = script_path(issue)
    if not force and is_up_to_date(issue, script_hash, entry):
        if not existing_script.exists() or hash_text(existing_script.read_text(encoding="utf-8")) != script_hash:
            existing_script.parent.mkdir(parents=True, exist_ok=True)
            existing_script.write_text(text, encoding="utf-8")
            print(f"Issue #{issue}: restored tracked audio script")
            return True
        print(f"Issue #{issue}: audio is up to date")
        return False

    print(f"Issue #{issue}: synthesizing {len(chunk_plan(text))} chunk(s)")
    output_path, duration_seconds = synthesize_mp3(issue, text)
    url, byte_size = upload_audio(issue, output_path)

    existing = dict(entry)
    for field in LEGACY_BRIEFLY_FIELDS:
        existing.pop(field, None)
    existing.update(
        {
            "audio_url": url,
            "audio_duration_seconds": duration_seconds,
            "audio_voice": AUDIO_VOICE,
            "audio_script_hash": script_hash,
            "generated_at": now_iso(),
            "byte_size": byte_size,
        }
    )
    manifest[issue] = existing
    existing_script.parent.mkdir(parents=True, exist_ok=True)
    existing_script.write_text(text, encoding="utf-8")
    write_manifest(manifest)
    print(f"Issue #{issue}: uploaded {url}")
    return True


def run_content_build() -> None:
    subprocess.run(
        [sys.executable, "pipeline/content/content.py", "build"],
        cwd=REPO,
        check=True,
    )


def cmd_build(args: argparse.Namespace) -> None:
    manifest = read_manifest()
    if scrub_legacy_briefly_fields(manifest) and not args.dry_run:
        write_manifest(manifest)
        print("Removed legacy briefly_synthesis fields from audio manifest")
    changed = False
    for issue in selected_issues(args):
        changed = build_issue(issue, manifest, dry_run=args.dry_run, force=args.force) or changed
    if changed and not args.dry_run:
        run_content_build()


def status_for_issue(issue: str, manifest: dict[str, dict[str, Any]]) -> tuple[str, str]:
    entry = manifest.get(issue, {})
    text = render_script(issue)
    script_hash = hash_text(text)
    if entry.get("audio_script_hash") != script_hash:
        return "render", "audio script changed"
    if entry.get("audio_voice") != AUDIO_VOICE:
        return "render", "voice changed"
    try:
        if not object_exists(issue):
            return "render", "S3 object missing"
    except Exception as exc:
        return "unknown", f"S3 HEAD failed: {exc}"
    return "skip", "up to date"


def cmd_status(args: argparse.Namespace) -> None:
    manifest = read_manifest()
    if scrub_legacy_briefly_fields(manifest):
        write_manifest(manifest)
        print("Removed legacy briefly_synthesis fields from audio manifest")
    for issue in selected_issues(args):
        state, reason = status_for_issue(issue, manifest)
        print(f"{state:7} #{issue}: {reason}")
        if state == "render":
            entry = manifest.get(issue, {})
            if entry.get("audio_url"):
                print(f"        current: {public_url(issue)}")


def main() -> None:
    parser = argparse.ArgumentParser(description="The Weekly Thing audio pipeline")
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="Render and upload audio")
    build_group = build_parser.add_mutually_exclusive_group()
    build_group.add_argument("--issue", help="Issue number to render")
    build_group.add_argument("--latest", action="store_true", help="Render latest issue only")
    build_group.add_argument("--all", action="store_true", help="Render all issues")
    build_parser.add_argument("--dry-run", action="store_true", help="Write script and chunk plan only")
    build_parser.add_argument("--force", action="store_true", help="Render even if cached")

    status_parser = subparsers.add_parser("status", help="Show issues needing render")
    status_group = status_parser.add_mutually_exclusive_group()
    status_group.add_argument("--issue", help="Issue number to inspect")
    status_group.add_argument("--latest", action="store_true", help="Inspect latest issue only")
    status_group.add_argument("--all", action="store_true", help="Inspect all issues")

    args = parser.parse_args()
    if args.command == "build":
        cmd_build(args)
    elif args.command == "status":
        cmd_status(args)


if __name__ == "__main__":
    main()
