"""CLI entry point for The Weekly Thing audio pipeline."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml
from dotenv import load_dotenv

from bumpers import (
    bumper_hashes,
    ensure_bumpers,
)
from manifest import (
    BUMPERS_KEY,
    bumper_path,
    hash_text,
    issue_entries,
    now_iso,
    read_manifest,
    read_script_review,
    read_script_status,
    script_path,
    SCRIPT_STATUS_SCHEMA_VERSION,
    write_manifest,
    write_script_review,
    write_script_status,
)
from script_validate import VALIDATOR_VERSION, run_validators
from cover import ensure_cover
from synthesize import (
    AUDIO_VOICE,
    LOUDNORM_VERSION,
    TMP_DIR,
    assemble_final,
    build_id3_metadata,
    chunk_plan,
    probe_duration_seconds,
    render_body,
)
from upload import (
    body_object_exists,
    body_public_url,
    copy_legacy_audio_to_body,
    download_body_if_present,
    object_exists,
    public_url,
    upload_audio,
    upload_body,
)

LEGACY_BRIEFLY_FIELDS = ("briefly_synthesis_hash", "briefly_synthesis_text", "briefly_syntheses")

REPO = Path(__file__).resolve().parents[2]
ARCHIVE_DIR = REPO / "apps" / "site" / "archive"
BODIES_DIR = REPO / "data" / "buttondown" / "bodies"
GENERATED_NOTICE_RE = re.compile(
    r"^<!-- Generated by (?:scripts/content|pipeline/content/content)\.py from data/buttondown; do not edit directly\. -->\r?\n"
)

sys.stdout.reconfigure(line_buffering=True)
load_dotenv(REPO / ".env")


def issue_sort_key(value: Any) -> tuple[int, str]:
    text = str(value)
    match = re.match(r"(\d+)", text)
    if not match:
        return (10**9, text)
    return (int(match.group(1)), text)


def parse_archive_file(path: Path) -> tuple[dict[str, Any], str]:
    raw = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.+?)\n---\n(.*)", raw, re.DOTALL)
    if not match:
        raise RuntimeError(f"{path} is missing YAML front matter")
    frontmatter = yaml.safe_load(match.group(1)) or {}
    body = GENERATED_NOTICE_RE.sub("", match.group(2)).strip()
    return frontmatter, body


def archive_path(issue: str) -> Path:
    path = ARCHIVE_DIR / f"{issue}.md"
    if not path.exists():
        raise RuntimeError(f"Archive issue not found: {path}")
    return path


def all_archive_issues() -> list[str]:
    issues = [
        path.stem
        for path in ARCHIVE_DIR.glob("*.md")
        if path.stem not in {"archive", "redirects"}
    ]
    return sorted(issues, key=issue_sort_key)


def latest_issue() -> str:
    latest: tuple[str, str] | None = None
    for issue in all_archive_issues():
        frontmatter, _ = parse_archive_file(archive_path(issue))
        publish_date = str(frontmatter.get("publish_date", ""))
        if latest is None or publish_date > latest[1]:
            latest = (issue, publish_date)
    if latest is None:
        raise RuntimeError("No archive issues found.")
    return latest[0]


def selected_issues(args: argparse.Namespace) -> list[str]:
    if args.issue:
        return [str(args.issue)]
    if args.all:
        issues = all_archive_issues()
    else:
        issues = [latest_issue()]
    limit = getattr(args, "limit", None)
    if limit:
        issues = issues[:limit]
    return issues


def per_block_transcript_dir(issue: str) -> Path:
    """Path to the Workshop-produced per-block transcript directory. Existence
    of this directory (with at least one .txt file) signals that audio should
    TTS each file as its own utterance — natural breath placement aligns with
    the editorial block boundaries instead of falling at MAX_CHARS packing
    seams. Legacy issues without this directory fall through to the single-
    script transform path (legacy.py / modern.py)."""
    return REPO / "data" / "issues" / str(issue) / "transcript"


def per_block_transcripts(issue: str) -> list[tuple[str, str]]:
    """Sorted list of (filename, content) for the per-block transcript files.
    Empty list if no transcript directory."""
    d = per_block_transcript_dir(issue)
    if not d.is_dir():
        return []
    out = []
    for path in sorted(d.glob("*.txt")):
        out.append((path.name, path.read_text(encoding="utf-8").strip()))
    return [(name, text) for name, text in out if text]


def render_script(issue: str) -> str:
    """Render the audio script from the archive markdown via script.py.

    Used by `scripts build` to (re)write the committed file. Audio build does
    not call this — it reads the committed script from disk.

    For Workshop-shipped issues (data/issues/{N}/transcript/ exists), returns
    the concatenation of the per-block files so script_hash stays meaningful
    end-to-end. The actual TTS path uses the per-block files directly."""
    blocks = per_block_transcripts(issue)
    if blocks:
        return "\n\n".join(text for _name, text in blocks) + "\n"

    from script import body_to_audio_script

    frontmatter, body = parse_archive_file(archive_path(issue))
    return body_to_audio_script(body, frontmatter)


def read_script(issue: str) -> str:
    """Read the committed audio script from disk. Source of truth for audio build.

    Per-block path: concatenation of data/issues/{N}/transcript/*.txt — never
    written to data/audio/scripts/, since the per-block files are themselves
    the cache. Legacy path: data/audio/scripts/{N}.txt (the single rendered
    transform output)."""
    blocks = per_block_transcripts(issue)
    if blocks:
        return "\n\n".join(text for _name, text in blocks) + "\n"

    path = script_path(issue)
    if not path.exists():
        raise RuntimeError(
            f"Audio script not found: {path}. Run "
            f"`python pipeline/audio/audio.py scripts build --issue {issue}` first."
        )
    return path.read_text(encoding="utf-8")


def write_script_file(issue: str, text: str) -> bool:
    """Write the script if it differs from the existing file. Returns True if written."""
    path = script_path(issue)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def scrub_legacy_briefly_fields(manifest: dict[str, dict[str, Any]]) -> bool:
    changed = False
    for entry in issue_entries(manifest).values():
        for field in LEGACY_BRIEFLY_FIELDS:
            if field in entry:
                entry.pop(field, None)
                changed = True
    return changed


def body_is_up_to_date(issue: str, script_hash: str, entry: dict[str, Any]) -> bool:
    return (
        entry.get("audio_script_hash") == script_hash
        and entry.get("audio_voice") == AUDIO_VOICE
        and body_object_exists(issue)
    )


def final_is_up_to_date(issue: str, entry: dict[str, Any]) -> bool:
    hashes = bumper_hashes()
    return (
        entry.get("intro_hash") == hashes["intro"]
        and entry.get("outro_hash") == hashes["outro"]
        and entry.get("loudnorm_version") == LOUDNORM_VERSION
        and object_exists(issue)
    )


def write_dry_run(issue: str, text: str) -> None:
    TMP_DIR.mkdir(parents=True, exist_ok=True)
    path = TMP_DIR / f"audio-script-{issue}.txt"
    path.write_text(text, encoding="utf-8")
    print(f"Dry run wrote {path.relative_to(REPO)}")
    print("Chunk plan:")
    for chunk in chunk_plan(text):
        print(f"  chunk {chunk['index']}: {chunk['characters']} characters")


def ensure_local_body(issue: str, entry: dict[str, Any]) -> Path | None:
    """Return a local body.mp3 for this issue, fetching from S3 if needed.

    Returns None if no body exists anywhere (caller must run TTS)."""
    workdir = TMP_DIR / str(issue)
    workdir.mkdir(parents=True, exist_ok=True)
    body_path = workdir / "body.mp3"
    if body_path.exists():
        return body_path
    if download_body_if_present(issue, body_path):
        return body_path
    return None


def maybe_promote_legacy_body(issue: str, entry: dict[str, Any]) -> str | None:
    """If a legacy published MP3 exists but no body MP3 yet, S3-copy it.

    The pre-bumper pipeline produced files with no intro/outro and no
    normalization — those files ARE valid body audio. Promoting them lets us
    reassemble with bumpers + loudnorm without paying TTS again."""
    if entry.get("audio_url") and not body_object_exists(issue):
        url = copy_legacy_audio_to_body(issue)
        if url:
            print(f"Issue #{issue}: promoted legacy audio to body slot")
        return url
    return None


def build_issue(
    issue: str,
    manifest: dict[str, dict[str, Any]],
    dry_run: bool,
    force: bool,
    reassemble_only: bool,
) -> bool:
    entry = dict(manifest.get(issue, {}))
    text = read_script(issue)
    script_hash = hash_text(text)
    # Per-block path: one TTS call per file under data/issues/{N}/transcript/,
    # so breath placement lands at editorial boundaries. Empty list → legacy
    # single-string path (chunk_text packs MAX_CHARS units).
    blocks = [text for _name, text in per_block_transcripts(issue)]

    if dry_run:
        write_dry_run(issue, text)
        return False

    body_fresh = body_is_up_to_date(issue, script_hash, entry)
    if (
        not body_fresh
        and not force
        and entry.get("audio_script_hash") == script_hash
        and entry.get("audio_voice") == AUDIO_VOICE
    ):
        promoted_url = maybe_promote_legacy_body(issue, entry)
        if promoted_url:
            entry["body_url"] = promoted_url
            body_fresh = True

    final_fresh = body_fresh and final_is_up_to_date(issue, entry)

    if not force and final_fresh:
        print(f"Issue #{issue}: audio is up to date")
        return False

    body_path: Path
    body_duration: int | None = None
    body_size: int | None = None
    body_url: str | None = entry.get("body_url")

    if force or not body_fresh:
        if reassemble_only:
            print(f"Issue #{issue}: skipping (body stale and --reassemble-only set)")
            return False
        chunk_count = len(blocks) if blocks else len(chunk_plan(text))
        mode = "per-block" if blocks else "legacy"
        print(f"Issue #{issue}: synthesizing body ({chunk_count} {mode} chunk(s))")
        body_path, body_duration = render_body(issue, text, blocks=blocks)
        body_url, body_size = upload_body(issue, body_path)
        print(f"Issue #{issue}: uploaded body {body_url}")
    else:
        local_body = ensure_local_body(issue, entry)
        if local_body is None:
            if reassemble_only:
                print(f"Issue #{issue}: skipping (no body in S3 and --reassemble-only set)")
                return False
            chunk_count = len(blocks) if blocks else len(chunk_plan(text))
            mode = "per-block" if blocks else "legacy"
            print(f"Issue #{issue}: body missing in S3, synthesizing ({chunk_count} {mode} chunk(s))")
            body_path, body_duration = render_body(issue, text, blocks=blocks)
            body_url, body_size = upload_body(issue, body_path)
            print(f"Issue #{issue}: uploaded body {body_url}")
        else:
            body_path = local_body
            print(f"Issue #{issue}: reusing existing body audio")

    intro_path = bumper_path("intro")
    outro_path = bumper_path("outro")
    if not intro_path.exists() or not outro_path.exists():
        raise RuntimeError(
            "Bumpers are missing. Run `python pipeline/audio/audio.py bumpers build` first."
        )

    frontmatter, _ = parse_archive_file(archive_path(issue))
    metadata = build_id3_metadata(issue, frontmatter)
    cover_path = ensure_cover(issue, frontmatter.get("image"))
    print(f"Issue #{issue}: assembling final with bumpers + loudnorm + tags")
    final_path, final_duration = assemble_final(
        issue, intro_path, body_path, outro_path, metadata, cover_path
    )
    final_url, final_size = upload_audio(issue, final_path)

    if body_duration is None and body_path.exists():
        body_duration = probe_duration_seconds(body_path)
    if body_size is None and body_path.exists():
        body_size = body_path.stat().st_size
    if body_url is None:
        body_url = body_public_url(issue)

    hashes = bumper_hashes()
    cleaned = {key: value for key, value in entry.items() if key not in LEGACY_BRIEFLY_FIELDS}
    cleaned.update(
        {
            "audio_url": final_url,
            "audio_duration_seconds": final_duration,
            "audio_byte_size": final_size,
            "audio_voice": AUDIO_VOICE,
            "audio_script_hash": script_hash,
            "body_url": body_url,
            "body_duration_seconds": body_duration,
            "body_byte_size": body_size,
            "intro_hash": hashes["intro"],
            "outro_hash": hashes["outro"],
            "loudnorm_version": LOUDNORM_VERSION,
            "generated_at": now_iso(),
        }
    )
    # Preserve back-compat field name some callers may still read.
    cleaned["byte_size"] = final_size
    manifest[issue] = cleaned

    write_manifest(manifest)
    print(f"Issue #{issue}: uploaded {final_url}")
    return True


def run_content_build() -> None:
    subprocess.run(
        [sys.executable, "pipeline/content/content.py", "build"],
        cwd=REPO,
        check=True,
    )


def cmd_build(args: argparse.Namespace) -> None:
    manifest = read_manifest()
    if scrub_legacy_briefly_fields(manifest) and not args.dry_run:
        write_manifest(manifest)
        print("Removed legacy briefly_synthesis fields from audio manifest")

    issues = selected_issues(args)
    if not args.dry_run:
        blocked = issues_blocked_by_validation(issues)
        if blocked:
            if args.all and not args.allow_unvalidated:
                print(
                    f"audio build --all: {len(blocked)} issue(s) blocked by validation. "
                    "Run `scripts build` and `scripts validate`, fix script.py until clean, "
                    "or pass --allow-unvalidated to override."
                )
                for issue, findings in blocked.items():
                    top = findings[0]
                    print(f"  #{issue}: {top.get('rule')} — {top.get('message', '')}")
                sys.exit(1)
            for issue, findings in blocked.items():
                top = findings[0]
                print(f"Issue #{issue}: warning — {top.get('rule')}: {top.get('message', '')}")

    if not args.dry_run:
        if ensure_bumpers(manifest, force=False):
            write_manifest(manifest)
    changed = False
    for issue in issues:
        try:
            changed = build_issue(
                issue,
                manifest,
                dry_run=args.dry_run,
                force=args.force,
                reassemble_only=args.reassemble_only,
            ) or changed
        except Exception as exc:  # noqa: BLE001 — keep batch moving on per-issue failure
            print(f"Issue #{issue}: failed ({exc.__class__.__name__}: {exc})")
            if args.fail_fast:
                raise
    if changed and not args.dry_run:
        run_content_build()


def cmd_bumpers(args: argparse.Namespace) -> None:
    manifest = read_manifest()
    changed = ensure_bumpers(manifest, force=args.force)
    if changed:
        write_manifest(manifest)


def status_for_issue(issue: str, manifest: dict[str, dict[str, Any]]) -> tuple[str, str]:
    entry = manifest.get(issue, {})
    if not script_path(issue).exists():
        return "scripts-missing", "no committed script (run `scripts build`)"
    text = read_script(issue)
    script_hash = hash_text(text)
    if entry.get("audio_voice") != AUDIO_VOICE:
        return "body-render", "voice changed"
    if entry.get("audio_script_hash") != script_hash:
        return "body-render", "audio script changed"
    try:
        if not body_object_exists(issue):
            if entry.get("audio_url") and object_exists(issue):
                return "promote", "legacy audio can be promoted to body slot (no TTS)"
            return "body-render", "body S3 object missing"
    except Exception as exc:
        return "unknown", f"S3 HEAD failed: {exc}"
    hashes = bumper_hashes()
    if entry.get("intro_hash") != hashes["intro"] or entry.get("outro_hash") != hashes["outro"]:
        return "reassemble", "bumper text changed"
    if entry.get("loudnorm_version") != LOUDNORM_VERSION:
        return "reassemble", f"loudnorm version is {LOUDNORM_VERSION}"
    try:
        if not object_exists(issue):
            return "reassemble", "final S3 object missing"
    except Exception as exc:
        return "unknown", f"S3 HEAD failed: {exc}"
    return "skip", "up to date"


def cmd_scripts_build(args: argparse.Namespace) -> None:
    written = 0
    for issue in selected_issues(args):
        text = render_script(issue)
        if write_script_file(issue, text):
            written += 1
            print(f"Issue #{issue}: wrote {script_path(issue).relative_to(REPO)}")
        else:
            print(f"Issue #{issue}: script unchanged")
    print(f"scripts build: {written} script(s) written/updated")


def _validation_result_for_issue(issue: str) -> dict[str, Any]:
    text = read_script(issue)
    errors, warnings = run_validators(text)
    return {
        "script_hash": hash_text(text),
        "validated_at": now_iso(),
        "errors": [finding.to_dict() for finding in errors],
        "warnings": [finding.to_dict() for finding in warnings],
    }


def cmd_scripts_validate(args: argparse.Namespace) -> None:
    status = read_script_status()
    status["schema_version"] = SCRIPT_STATUS_SCHEMA_VERSION
    status["validator_version"] = VALIDATOR_VERSION
    issues_status = status.setdefault("issues", {})
    total_errors = 0
    total_warnings = 0
    issues_with_errors: list[str] = []
    for issue in selected_issues(args):
        try:
            result = _validation_result_for_issue(issue)
        except RuntimeError as exc:
            print(f"Issue #{issue}: skipped ({exc})")
            continue
        issues_status[issue] = result
        n_errors = len(result["errors"])
        n_warnings = len(result["warnings"])
        total_errors += n_errors
        total_warnings += n_warnings
        if n_errors:
            issues_with_errors.append(issue)
        marker = "ERROR" if n_errors else ("warn" if n_warnings else "ok")
        print(f"{marker:5} #{issue}: {n_errors} error(s), {n_warnings} warning(s)")
        for finding in result["errors"][:5]:
            print(f"      E line {finding['line']} {finding['rule']}: {finding['snippet']}")
        for finding in result["warnings"][:3]:
            print(f"      W line {finding['line']} {finding['rule']}: {finding['snippet']}")
    write_script_status(status)
    print(
        f"scripts validate: {total_errors} error(s), {total_warnings} warning(s) "
        f"across {len(issues_status)} tracked issue(s)"
    )
    if issues_with_errors:
        print(f"Issues with errors: {', '.join(issues_with_errors)}")
        sys.exit(1)


def _body_text(issue: str) -> str:
    path = BODIES_DIR / f"{issue}.md"
    if not path.exists():
        raise RuntimeError(f"Body markdown not found: {path}")
    return path.read_text(encoding="utf-8")


def cmd_scripts_review(args: argparse.Namespace) -> None:
    from concurrent.futures import ThreadPoolExecutor, as_completed
    from script_review import HAIKU_MODEL, REVIEWER_VERSION, make_client, review_issue

    review = read_script_review()
    review["schema_version"] = SCRIPT_STATUS_SCHEMA_VERSION
    review["reviewer_version"] = REVIEWER_VERSION
    review["model"] = HAIKU_MODEL
    issues_review = review.setdefault("issues", {})

    issues = selected_issues(args)
    work: list[tuple[str, str, str, str]] = []  # (issue, script_hash, body, script)
    skipped = 0
    for issue in issues:
        if not script_path(issue).exists():
            print(f"Issue #{issue}: skipped (no committed script)")
            continue
        script = script_path(issue).read_text(encoding="utf-8")
        script_hash = hash_text(script)
        existing = issues_review.get(issue)
        if (
            not args.force
            and isinstance(existing, dict)
            and existing.get("script_hash") == script_hash
            and existing.get("reviewer_version") == REVIEWER_VERSION
        ):
            skipped += 1
            continue
        try:
            body = _body_text(issue)
        except RuntimeError as exc:
            print(f"Issue #{issue}: skipped ({exc})")
            continue
        work.append((issue, script_hash, body, script))

    print(f"scripts review: {len(work)} to review, {skipped} cached, {len(issues) - len(work) - skipped} skipped")
    if not work:
        write_script_review(review)
        return

    client = make_client()
    total_cost = 0.0
    total_errors = 0
    total_warnings = 0
    issues_with_errors: list[str] = []

    def _do(item):
        issue, script_hash, body, script = item
        result, usage = review_issue(client, issue, body, script)
        return issue, script_hash, result, usage

    workers = max(1, args.workers)
    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = [pool.submit(_do, item) for item in work]
        for future in as_completed(futures):
            try:
                issue, script_hash, result, usage = future.result()
            except Exception as exc:  # noqa: BLE001
                print(f"Issue review failed: {exc.__class__.__name__}: {exc}")
                continue
            errors = [f for f in result.findings if f.severity == "error"]
            warnings = [f for f in result.findings if f.severity == "warning"]
            issues_review[issue] = {
                "script_hash": script_hash,
                "reviewed_at": now_iso(),
                "reviewer_version": REVIEWER_VERSION,
                "model": HAIKU_MODEL,
                "usage": usage,
                "errors": [f.model_dump() for f in errors],
                "warnings": [f.model_dump() for f in warnings],
            }
            total_cost += usage.get("est_cost_usd", 0)
            total_errors += len(errors)
            total_warnings += len(warnings)
            if errors:
                issues_with_errors.append(issue)
            marker = "ERROR" if errors else ("warn" if warnings else "ok")
            print(
                f"{marker:5} #{issue}: {len(errors)} error(s), {len(warnings)} warning(s) "
                f"[~${usage.get('est_cost_usd', 0):.4f}]"
            )
            for f in errors[:3]:
                print(f"      E {f.where}: {f.what}")
            for f in warnings[:2]:
                print(f"      W {f.where}: {f.what}")

    write_script_review(review)
    print(
        f"scripts review: {total_errors} error(s), {total_warnings} warning(s), "
        f"~${total_cost:.4f} spent"
    )
    if issues_with_errors:
        print(f"Issues with errors: {', '.join(sorted(issues_with_errors, key=issue_sort_key))}")
        sys.exit(1)


def cmd_scripts(args: argparse.Namespace) -> None:
    if args.scripts_command == "build":
        cmd_scripts_build(args)
    elif args.scripts_command == "validate":
        cmd_scripts_validate(args)
    elif args.scripts_command == "review":
        cmd_scripts_review(args)


def issues_blocked_by_validation(issues: list[str]) -> dict[str, list[dict[str, Any]]]:
    """Return {issue: [error findings]} for issues that fail validation against the script on disk."""
    status = read_script_status()
    issues_status = status.get("issues") or {}
    blocked: dict[str, list[dict[str, Any]]] = {}
    for issue in issues:
        path = script_path(issue)
        if not path.exists():
            blocked[issue] = [{"rule": "scripts_missing", "message": "no committed script"}]
            continue
        text = path.read_text(encoding="utf-8")
        current_hash = hash_text(text)
        record = issues_status.get(issue)
        if not isinstance(record, dict):
            blocked[issue] = [{"rule": "unvalidated", "message": "no validation record"}]
            continue
        if record.get("script_hash") != current_hash:
            blocked[issue] = [{"rule": "stale_validation", "message": "validation predates current script"}]
            continue
        errors = record.get("errors") or []
        if errors:
            blocked[issue] = errors
    return blocked


def cmd_status(args: argparse.Namespace) -> None:
    manifest = read_manifest()
    if scrub_legacy_briefly_fields(manifest):
        write_manifest(manifest)
        print("Removed legacy briefly_synthesis fields from audio manifest")
    for issue in selected_issues(args):
        state, reason = status_for_issue(issue, manifest)
        print(f"{state:12} #{issue}: {reason}")
        if state in {"body-render", "reassemble"}:
            entry = manifest.get(issue, {})
            if entry.get("audio_url"):
                print(f"             current: {public_url(issue)}")


def main() -> None:
    parser = argparse.ArgumentParser(description="The Weekly Thing audio pipeline")
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="Render and upload audio")
    build_group = build_parser.add_mutually_exclusive_group()
    build_group.add_argument("--issue", help="Issue number to render")
    build_group.add_argument("--latest", action="store_true", help="Render latest issue only")
    build_group.add_argument("--all", action="store_true", help="Render all issues")
    build_parser.add_argument("--dry-run", action="store_true", help="Write script and chunk plan only")
    build_parser.add_argument("--force", action="store_true", help="Render even if cached")
    build_parser.add_argument("--limit", type=int, help="Cap how many issues are processed in this run")
    build_parser.add_argument(
        "--reassemble-only",
        action="store_true",
        help="Only reassemble final MP3s for issues that already have a body in S3 (no TTS)",
    )
    build_parser.add_argument("--fail-fast", action="store_true", help="Abort on first per-issue failure")
    build_parser.add_argument(
        "--allow-unvalidated",
        action="store_true",
        help="Allow --all to proceed even if some scripts have validation errors",
    )

    bumpers_parser = subparsers.add_parser("bumpers", help="Manage podcast intro/outro bumpers")
    bumpers_subparsers = bumpers_parser.add_subparsers(dest="bumpers_command", required=True)
    bumpers_build = bumpers_subparsers.add_parser("build", help="Render bumpers if missing or text changed")
    bumpers_build.add_argument("--force", action="store_true", help="Re-render even if up to date")

    scripts_parser = subparsers.add_parser("scripts", help="Manage committed audio scripts")
    scripts_subparsers = scripts_parser.add_subparsers(dest="scripts_command", required=True)
    for action in ("build", "validate", "review"):
        sp = scripts_subparsers.add_parser(action, help=f"{action} audio scripts")
        group = sp.add_mutually_exclusive_group()
        group.add_argument("--issue", help="Issue number")
        group.add_argument("--latest", action="store_true", help=f"{action} latest issue only")
        group.add_argument("--all", action="store_true", help=f"{action} every issue")
        sp.add_argument("--limit", type=int, help="Cap how many issues are processed")
        if action == "review":
            sp.add_argument("--force", action="store_true", help="Re-review even if cached")
            sp.add_argument("--workers", type=int, default=8, help="Parallel reviewers (default 8)")

    status_parser = subparsers.add_parser("status", help="Show issues needing render")
    status_group = status_parser.add_mutually_exclusive_group()
    status_group.add_argument("--issue", help="Issue number to inspect")
    status_group.add_argument("--latest", action="store_true", help="Inspect latest issue only")
    status_group.add_argument("--all", action="store_true", help="Inspect all issues")
    status_parser.add_argument("--limit", type=int, help="Cap how many issues are inspected")

    args = parser.parse_args()
    if args.command == "build":
        cmd_build(args)
    elif args.command == "bumpers":
        if args.bumpers_command == "build":
            cmd_bumpers(args)
    elif args.command == "scripts":
        cmd_scripts(args)
    elif args.command == "status":
        cmd_status(args)


if __name__ == "__main__":
    main()
