"""Read full archive issue bodies on demand.

The `get_issue` and `get_section` agent tools call into `read_issue` here.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any, Iterable, Optional

import yaml

REPO = Path(__file__).resolve().parents[3]
ARCHIVE_DIR = REPO / "apps" / "site" / "archive"

logger = logging.getLogger("workshop.archive")

GENERATED_NOTICE_RE = re.compile(
    r"^<!--\s*Generated by [^>]+?-->\s*\n?",
    re.MULTILINE,
)


def latest_issue_number(issues: Iterable[dict[str, Any]]) -> Optional[int]:
    """Largest pure-integer issue number in the corpus, or None."""
    best: Optional[int] = None
    for issue in issues:
        n = issue.get("number")
        if isinstance(n, int):
            cand = n
        elif isinstance(n, str) and n.isdigit():
            cand = int(n)
        else:
            continue
        if best is None or cand > best:
            best = cand
    return best


def read_issue(number: int) -> Optional[dict[str, Any]]:
    """Read `apps/site/archive/{n}.md`. Returns dict with `frontmatter`, `body`."""
    path = ARCHIVE_DIR / f"{number}.md"
    if not path.exists():
        # Some issues are suffixed (e.g. `140-special`); try a glob.
        candidates = sorted(ARCHIVE_DIR.glob(f"{number}-*.md"))
        if not candidates:
            return None
        path = candidates[0]
    raw = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.+?)\n---\n(.*)", raw, re.DOTALL)
    if not match:
        return {"number": number, "frontmatter": {}, "body": raw, "path": path.name}
    try:
        fm = yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError:
        fm = {}
    body = GENERATED_NOTICE_RE.sub("", match.group(2)).strip()
    return {"number": number, "frontmatter": fm, "body": body, "path": path.name}
