"""Read full archive issue bodies on demand.

When a persona's user message names a specific issue (`#346`, `issue 346`,
`the latest issue`), the handler should inject that issue's full body into
the LLM call. The retrieval/BM25 path is for fuzzy "find what's related";
this is for "Jamie literally named the issue."
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any, Iterable, Optional

import yaml

REPO = Path(__file__).resolve().parents[3]
ARCHIVE_DIR = REPO / "apps" / "site" / "archive"

logger = logging.getLogger("workshop.archive")

# `#346`, `#346-special`, `issue 346`, `issue #346`
ISSUE_NUM_RE = re.compile(
    r"(?:#|issue\s+#?)(\d{1,4})(?:-[\w-]+)?",
    re.IGNORECASE,
)
LATEST_RE = re.compile(
    r"\b(?:the\s+)?"
    r"(?:latest|most\s+recent|last|newest|previous)\s+"
    r"(?:issue|one|week|weekly\s+thing|edition)"
    r"|"
    r"\bthis\s+week'?s\s+(?:issue|one|edition|weekly\s+thing)"
    r"|"
    r"\blast\s+week'?s\s+(?:issue|one|edition|weekly\s+thing)",
    re.IGNORECASE,
)
GENERATED_NOTICE_RE = re.compile(
    r"^<!--\s*Generated by [^>]+?-->\s*\n?",
    re.MULTILINE,
)
DEFAULT_MAX_CHARS = 24_000


def latest_issue_number(issues: Iterable[dict[str, Any]]) -> Optional[int]:
    """Largest pure-integer issue number in the corpus, or None."""
    best: Optional[int] = None
    for issue in issues:
        n = issue.get("number")
        if isinstance(n, int):
            cand = n
        elif isinstance(n, str) and n.isdigit():
            cand = int(n)
        else:
            continue
        if best is None or cand > best:
            best = cand
    return best


def find_issue_refs(text: str, latest_number: Optional[int] = None) -> list[int]:
    """Return distinct issue numbers explicitly referenced in `text`."""
    if not text:
        return []
    nums = {int(m) for m in ISSUE_NUM_RE.findall(text)}
    if latest_number is not None and LATEST_RE.search(text):
        nums.add(latest_number)
    return sorted(nums)


def read_issue(number: int) -> Optional[dict[str, Any]]:
    """Read `apps/site/archive/{n}.md`. Returns dict with `frontmatter`, `body`."""
    path = ARCHIVE_DIR / f"{number}.md"
    if not path.exists():
        # Some issues are suffixed (e.g. `140-special`); try a glob.
        candidates = sorted(ARCHIVE_DIR.glob(f"{number}-*.md"))
        if not candidates:
            return None
        path = candidates[0]
    raw = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.+?)\n---\n(.*)", raw, re.DOTALL)
    if not match:
        return {"number": number, "frontmatter": {}, "body": raw, "path": path.name}
    try:
        fm = yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError:
        fm = {}
    body = GENERATED_NOTICE_RE.sub("", match.group(2)).strip()
    return {"number": number, "frontmatter": fm, "body": body, "path": path.name}


def format_issue_for_context(issue: dict[str, Any], *, max_chars: int = DEFAULT_MAX_CHARS) -> str:
    fm = issue.get("frontmatter") or {}
    number = issue.get("number")
    subject = fm.get("subject", "(no subject)")
    date = (fm.get("publish_date") or "")[:10]
    body = issue.get("body", "")
    truncated = ""
    if len(body) > max_chars:
        body = body[:max_chars]
        truncated = f"\n\n[…truncated to {max_chars:,} chars; full body is longer]"
    head = f"# Full text — Issue #{number} ({date}): \"{subject}\""
    return f"{head}\n\n{body}{truncated}"


def expand_refs(
    text: str,
    *,
    latest_number: Optional[int] = None,
    max_chars: int = DEFAULT_MAX_CHARS,
) -> str:
    """Return a single formatted block with every referenced issue's body, or ''."""
    refs = find_issue_refs(text, latest_number)
    if not refs:
        return ""
    blocks: list[str] = []
    for n in refs:
        issue = read_issue(n)
        if issue is None:
            blocks.append(f"# Issue #{n}\n\n(no archive file found at apps/site/archive/{n}.md)")
            continue
        blocks.append(format_issue_for_context(issue, max_chars=max_chars))
    if blocks:
        logger.info("expanded issue refs: %s", refs)
    return "\n\n---\n\n".join(blocks)
