const { test, expect } = require('@playwright/test');

test('main navigation stays on one row at mobile widths', async ({ page }) => {
  const sizes = [
    { width: 320, height: 568 },
    { width: 360, height: 740 },
    { width: 390, height: 844 },
    { width: 414, height: 896 },
    { width: 430, height: 932 },
  ];

  for (const viewport of sizes) {
    await page.setViewportSize(viewport);
    await page.goto('/', { waitUntil: 'domcontentloaded' });

    const navLayout = await page.locator('.site-nav').evaluate((nav) => {
      const links = Array.from(nav.querySelectorAll('a'));
      const rowTops = new Set(links.map((link) => Math.round(link.getBoundingClientRect().top)));
      const firstLink = links[0].getBoundingClientRect();

      return {
        rows: rowTops.size,
        bodyScrollWidth: document.documentElement.scrollWidth,
        viewportWidth: window.innerWidth,
        firstLinkLeft: Math.round(firstLink.left),
      };
    });

    expect(navLayout.rows, `${viewport.width}px nav rows`).toBe(1);
    expect(navLayout.bodyScrollWidth, `${viewport.width}px body width`).toBeLessThanOrEqual(navLayout.viewportWidth);
    expect(navLayout.firstLinkLeft, `${viewport.width}px first link`).toBeGreaterThanOrEqual(0);

    const lastLinkRight = await page.locator('.site-nav').evaluate((nav) => {
      nav.scrollLeft = nav.scrollWidth;
      return Math.round(nav.querySelector('a:last-child').getBoundingClientRect().right);
    });
    expect(lastLinkRight, `${viewport.width}px last link after scrolling`).toBeLessThanOrEqual(
      viewport.width,
    );
  }
});

test('legacy Thingy URL redirects to standalone chat', async ({ page }) => {
  await page.route('https://thingy.thingelstad.com/chat/?prompt=RSS', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'text/html',
      body: '<!doctype html><title>Thingy Chat</title><h1>Thingy Chat</h1>',
    });
  });

  await page.goto('/thingy/?prompt=RSS#sources');

  await expect(page).toHaveURL('https://thingy.thingelstad.com/chat/?prompt=RSS#sources');
  await expect(page.locator('h1')).toHaveText('Thingy Chat');
});

test('old librarian URL redirects to standalone chat', async ({ page }) => {
  await page.route('https://thingy.thingelstad.com/chat/', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'text/html',
      body: '<!doctype html><title>Thingy Chat</title><h1>Thingy Chat</h1>',
    });
  });

  await page.goto('/librarian/');

  await expect(page).toHaveURL('https://thingy.thingelstad.com/chat/');
  await expect(page.locator('h1')).toHaveText('Thingy Chat');
});

test('issue text and RSS carry no generated-file notice', async ({ request }) => {
  // 294 is a back-catalogue page re-rendered by WT Builder; 351 was authored there.
  for (const path of ['/archive/294.txt', '/archive/351.txt', '/rss']) {
    const res = await request.get(path);
    expect(res.ok(), path).toBeTruthy();
    const text = await res.text();
    expect(text, path).not.toContain('Generated by');
    expect(text, path).not.toContain('do not edit directly');
  }
});

test('the transcript panel shows WebVTT escapes as the characters they stand for, never as markup', async ({ page }) => {
  // WT Builder writes cue text with the standard WebVTT escapes (&amp; &lt;
  // &gt;); the panel decodes them and still sets each cue as text. Nothing
  // leaves the machine: every request off 127.0.0.1 is refused, and the
  // .vtt is served here.
  const vtt = [
    'WEBVTT',
    '',
    '00:00:00.000 --> 00:00:02.000',
    '<v Jamie>Procter &amp; Gamble say 3 &lt; 4, and &lt;b&gt;this&lt;/b&gt; is not bold --&gt; ever.',
    '',
    '00:00:02.000 --> 00:00:03.000',
    '<v Thingy>&lt;img src=x onerror="window.pwned=1"&gt; and &amp;amp; stays one escape.',
    '',
  ].join('\n');
  await page.route((url) => url.hostname !== '127.0.0.1', (route) => route.abort());
  await page.route(/\.vtt$/, (route) =>
    route.fulfill({ status: 200, contentType: 'text/vtt', headers: { 'Access-Control-Allow-Origin': '*' }, body: vtt }),
  );

  await page.goto('/archive/351/', { waitUntil: 'domcontentloaded' });
  await page.locator('.issue-transcript summary').click();

  const cues = page.locator('.issue-transcript-body .issue-cue > span:last-child');
  await expect(cues).toHaveText([
    'Procter & Gamble say 3 < 4, and <b>this</b> is not bold --> ever.',
    '<img src=x onerror="window.pwned=1"> and &amp; stays one escape.',
  ]);
  await expect(page.locator('.issue-transcript-body b')).toHaveCount(0);
  await expect(page.locator('.issue-transcript-body img[src="x"]')).toHaveCount(0);
  expect(await page.evaluate(() => window.pwned)).toBeUndefined();
});
