import importlib.util
import json
import tempfile
import unittest
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "pipeline" / "corpus" / "build.py"

spec = importlib.util.spec_from_file_location("pipeline_corpus_build", SCRIPT)
corpus = importlib.util.module_from_spec(spec)
spec.loader.exec_module(corpus)


def _empty_site(root: Path) -> Path:
    """Build a site_dir scaffold that has no about/support content — used
    to keep the issue-only tests from picking up the real ``apps/site``."""
    site = root / "site"
    site.mkdir()
    (site / "_data").mkdir()
    return site


class LibrarianCorpusTests(unittest.TestCase):
    def test_builds_chunks_with_issue_citations(self):
        with tempfile.TemporaryDirectory() as tmp:
            archive = Path(tmp) / "archive"
            archive.mkdir()
            (archive / "1.md").write_text(
                "<!-- Generated by pipeline/content/content.py from data/issues; do not edit directly. -->\n"
                "---\n"
                "number: 1\n"
                "subject: Weekly Thing 1\n"
                "publish_date: 2026-01-01T12:00:00Z\n"
                "---\n"
                "Intro paragraph.\n\n"
                "## Open Web\n\n"
                "RSS and personal websites are useful.\n",
                encoding="utf-8",
            )

            result = corpus.build_corpus(
                archive,
                site_dir=_empty_site(Path(tmp)),
                faq_path=Path(tmp) / "missing-faq.json",
            )

        self.assertEqual(result["issue_count"], 1)
        self.assertGreaterEqual(result["chunk_count"], 1)
        self.assertEqual(result["version"], 2)
        self.assertIn("topics", result)
        self.assertIn("summary", result["issues"][0])
        self.assertIn("body_hash", result["issues"][0])
        self.assertEqual(result["chunks"][0]["issue_number"], 1)
        self.assertEqual(result["chunks"][0]["url"], "/archive/1/")
        self.assertEqual(result["chunks"][0]["source_kind"], "chunk")
        self.assertIn("content_kind", result["chunks"][0])

    def test_rejects_template_leaks(self):
        with tempfile.TemporaryDirectory() as tmp:
            archive = Path(tmp) / "archive"
            archive.mkdir()
            (archive / "1.md").write_text(
                "---\nnumber: 1\nsubject: Weekly Thing 1\n---\n"
                "Hello {{ subscriber.email }}\n",
                encoding="utf-8",
            )

            with self.assertRaisesRegex(RuntimeError, "Template/generated content leaked"):
                corpus.build_corpus(
                    archive,
                    site_dir=_empty_site(Path(tmp)),
                    faq_path=Path(tmp) / "missing-faq.json",
                )

    def _seed_archive(self, archive: Path) -> None:
        (archive / "1.md").write_text(
            "---\nnumber: 1\nsubject: Weekly Thing 1\npublish_date: 2017-05-13T12:00:00Z\n---\nFirst issue.\n",
            encoding="utf-8",
        )
        (archive / "349.md").write_text(
            "---\nnumber: 349\nsubject: WT349 — Owning the Rails\npublish_date: 2026-05-23T12:00:00Z\n---\nLatest issue.\n",
            encoding="utf-8",
        )

    def test_about_page_chunk_carries_origin_story(self):
        # About.njk content lands as a site_page chunk so retrieval can
        # surface the founding date / cadence / podcast availability
        # without Thingy having to call a dedicated tool.
        with tempfile.TemporaryDirectory() as tmp:
            archive = Path(tmp) / "archive"
            archive.mkdir()
            self._seed_archive(archive)
            site = _empty_site(Path(tmp))
            (site / "about.njk").write_text(
                "---\nlayout: layouts/page.njk\npermalink: /about/\n---\n"
                "<p>The Weekly Thing started in May 2017 as a simple experiment.</p>"
                "<p>Selected issues are also available as audio via the podcast feed.</p>",
                encoding="utf-8",
            )
            result = corpus.build_corpus(
                archive,
                site_dir=site,
                faq_path=Path(tmp) / "missing-faq.json",
            )
        about = [c for c in result["chunks"] if c["source_kind"] == "site_page" and c["url"] == "/about/"]
        self.assertTrue(about, "expected at least one /about/ site_page chunk")
        about_text = " ".join(c["text"] for c in about)
        self.assertIn("May 2017", about_text)
        self.assertIn("podcast", about_text.lower())
        # No issue_number on site_page chunks.
        self.assertIsNone(about[0]["issue_number"])
        self.assertEqual(about[0]["section"], "About")

    def test_members_page_and_nonprofit_history_chunks(self):
        # Both the prose page (/members/) and a dedicated structured
        # nonprofit-history chunk land in the corpus so Thingy can quote
        # the offer + the past years' picks directly.
        with tempfile.TemporaryDirectory() as tmp:
            archive = Path(tmp) / "archive"
            archive.mkdir()
            self._seed_archive(archive)
            site = _empty_site(Path(tmp))
            (site / "support.njk").write_text(
                "---\npermalink: /members/\n---\n"
                "<h1>Supporting Membership</h1>"
                "<p>Members fund a nonprofit selected each year. {% if support.yearly_price %}Yearly is ${{ support.yearly_price }}.{% endif %}</p>",
                encoding="utf-8",
            )
            (site / "_data" / "support.json").write_text(json.dumps({
                "yearly_price": 48,
                "current": {
                    "nonprofit": "Signal",
                    "short_name": "Signal",
                    "year_label": "Ninth Year",
                    "description": "Encrypted messaging nonprofit.",
                },
                "past": [
                    {"nonprofit": "Electronic Frontier Foundation", "short_name": "EFF", "year_label": "Year 8", "amount_raised": 1164.92},
                    {"nonprofit": "Creative Commons", "year": 2024},
                ],
            }), encoding="utf-8")
            result = corpus.build_corpus(
                archive,
                site_dir=site,
                faq_path=Path(tmp) / "missing-faq.json",
            )
        members = [c for c in result["chunks"] if c["url"] == "/members/" and c["section"] == "Supporting Membership"]
        history = [c for c in result["chunks"] if c["id"] == "site:nonprofit-history:0"]
        self.assertTrue(members, "expected /members/ site_page chunks")
        self.assertTrue(history, "expected a site:nonprofit-history chunk")
        # The prose chunk knows about the current nonprofit + price.
        members_text = " ".join(c["text"] for c in members)
        self.assertIn("Members fund a nonprofit", members_text)
        # The history chunk lists past nonprofits with their year + amount.
        history_text = history[0]["text"]
        self.assertIn("Signal", history_text)
        self.assertIn("Electronic Frontier Foundation", history_text)
        self.assertIn("Year 8", history_text)
        self.assertIn("$1,165", history_text)
        self.assertIn("Creative Commons", history_text)

    def test_faq_entries_become_chunks(self):
        with tempfile.TemporaryDirectory() as tmp:
            archive = Path(tmp) / "archive"
            archive.mkdir()
            self._seed_archive(archive)
            site = _empty_site(Path(tmp))
            faq_path = Path(tmp) / "faq.json"
            faq_path.write_text(json.dumps({
                "sections": [
                    {
                        "title": "The Basics",
                        "entries": [
                            {"question": "What is the Weekly Thing?", "answer": "A weekly newsletter."},
                            {"question": "How long has it been running?", "answer": "Over {{yearsActive}} years and {{issueCount}} issues."},
                        ],
                    },
                    {
                        "title": "Membership",
                        "entries": [
                            {"question": "Does it cost anything?", "answer": "No, the newsletter is free."},
                        ],
                    },
                ]
            }), encoding="utf-8")
            result = corpus.build_corpus(archive, site_dir=site, faq_path=faq_path)
        faq = [c for c in result["chunks"] if c["source_kind"] == "faq"]
        self.assertEqual(len(faq), 3)
        # Stable id shape — section slug + entry index.
        ids = {c["id"] for c in faq}
        self.assertIn("faq:the-basics:0", ids)
        self.assertIn("faq:the-basics:1", ids)
        self.assertIn("faq:membership:0", ids)
        # Interpolation resolved against the archive we seeded (2 issues,
        # spanning 2017 → 2026, so 10 years active).
        running_text = next(c["text"] for c in faq if c["id"] == "faq:the-basics:1")
        self.assertIn("10 years and 2 issues", running_text)
        # Section name preserved as the chunk label.
        membership_chunk = next(c for c in faq if c["id"] == "faq:membership:0")
        self.assertEqual(membership_chunk["section"], "Membership")
        self.assertEqual(membership_chunk["url"], "/faq/")

    def test_privacy_denylist_blocks_subscriber_count_text(self):
        # A future regression that lets stats.subscriber_count leak into
        # about.njk / support.njk must fail the corpus build loudly.
        with tempfile.TemporaryDirectory() as tmp:
            archive = Path(tmp) / "archive"
            archive.mkdir()
            self._seed_archive(archive)
            site = _empty_site(Path(tmp))
            (site / "about.njk").write_text(
                "---\npermalink: /about/\n---\n"
                "<p>The Weekly Thing has subscriber_count readers.</p>",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(RuntimeError, "Privacy denylist"):
                corpus.build_corpus(
                    archive, site_dir=site, faq_path=Path(tmp) / "missing-faq.json",
                )


if __name__ == "__main__":
    unittest.main()
