import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
SCRIPTS = REPO / "scripts"
sys.path.insert(0, str(SCRIPTS))

spec = importlib.util.spec_from_file_location("content", SCRIPTS / "content.py")
content = importlib.util.module_from_spec(spec)
spec.loader.exec_module(content)


class ContentPipelineTests(unittest.TestCase):
    def test_canonical_hash_ignores_fetch_metadata(self):
        base = {
            "id": "em_1",
            "number": 1,
            "subject": "Weekly Thing 1",
            "description": "Description",
            "body": "Body",
            "image": "",
            "slug": "one",
            "publish_date": "2026-01-01T12:00:00Z",
            "absolute_url": "https://example.com/archive/1/",
            "email_type": "public",
            "status": "sent",
            "secondary_id": None,
            "fetched_at": "2026-01-01T12:00:01Z",
            "source_hash": "old",
        }
        changed_metadata = {**base, "fetched_at": "2026-01-02T12:00:01Z", "source_hash": "new"}
        changed_body = {**base, "body": "Changed"}

        self.assertEqual(content.canonical_hash(base), content.canonical_hash(changed_metadata))
        self.assertNotEqual(content.canonical_hash(base), content.canonical_hash(changed_body))

    def test_archive_parse_preserves_raw_body(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "1.md"
            path.write_text(
                "<!-- Generated by scripts/content.py from data/buttondown; do not edit directly. -->\n"
                "---\nsubject: Weekly Thing 1\nslug: '1'\nimage: ''\n---\n"
                "Line one\n\n{{ unsubscribe_url }}\n",
                encoding="utf-8",
            )

            front_matter, body = content.parse_archive_file(path)

        self.assertEqual(front_matter["subject"], "Weekly Thing 1")
        self.assertEqual(body, "Line one\n\n{{ unsubscribe_url }}")

    def test_write_snapshot_splits_metadata_and_body(self):
        original_snapshot_dir = content.SNAPSHOT_DIR
        original_body_dir = content.BODY_DIR
        try:
            with tempfile.TemporaryDirectory() as tmp:
                root = Path(tmp)
                content.SNAPSHOT_DIR = root / "emails"
                content.BODY_DIR = root / "bodies"
                snapshot = content.make_snapshot(
                    {
                        "id": "em_1",
                        "number": 1,
                        "subject": "Weekly Thing 1",
                        "description": "",
                        "body": "Line one\n\n{{ email_url }}\n",
                        "image": "",
                        "slug": "1",
                        "publish_date": "2026-01-01T12:00:00Z",
                        "absolute_url": "https://example.com/archive/1/",
                        "email_type": "public",
                        "status": "sent",
                        "secondary_id": None,
                    },
                    fetched_at="2026-01-01T12:00:01Z",
                )

                content.write_snapshot(snapshot)
                metadata = json.loads((root / "emails" / "1.json").read_text(encoding="utf-8"))
                body = (root / "bodies" / "1.md").read_text(encoding="utf-8")
        finally:
            content.SNAPSHOT_DIR = original_snapshot_dir
            content.BODY_DIR = original_body_dir

        self.assertNotIn("body", metadata)
        self.assertEqual(metadata["body_path"], "data/buttondown/bodies/1.md")
        self.assertEqual(body, "Line one\n\n{{ email_url }}\n")

    def test_archive_body_removes_personalized_subscriber_blocks(self):
        issue = {
            "number": 1,
            "subject": "Weekly Thing 1",
            "absolute_url": "https://weekly.thingelstad.com/archive/1/",
            "body": (
                "<!-- buttondown-editor-mode: plaintext -->Intro\n\n"
                "{% if subscriber.subscriber_type == 'premium' %}\nPremium only\n"
                "{% else %}\nUpsell {{ subscriber.email | urlencode }}\n{% endif %}\n\n"
                "Outro"
            ),
        }

        self.assertEqual(content.archive_body_from_issue(issue), "Intro\n\nOutro")

    def test_archive_body_renders_web_branch_for_medium(self):
        issue = {
            "number": 297,
            "subject": "Weekly Thing 297",
            "absolute_url": "https://weekly.thingelstad.com/archive/297/",
            "body": (
                "## Straw Poll\n\n"
                "{% if medium == 'email' %}\n{{ survey.strawpoll297 }}\n"
                "{% else %}\n_You must [subscribe]({{ subscribe_url }}) to respond._\n{% endif %}"
            ),
        }

        self.assertEqual(
            content.archive_body_from_issue(issue),
            "## Straw Poll\n\n_You must [subscribe](https://weekly.thingelstad.com/) to respond._",
        )

    def test_archive_body_replaces_public_email_variables(self):
        issue = {
            "number": 1,
            "subject": "Weekly Thing 1",
            "absolute_url": "https://weekly.thingelstad.com/archive/1/",
            "body": "Share [{{ email.subject }}]({{ email_url }}) and [LinkedIn]({{email_link}})",
        }

        self.assertEqual(
            content.archive_body_from_issue(issue),
            "Share [Weekly Thing 1](https://weekly.thingelstad.com/archive/1/) and [LinkedIn](https://weekly.thingelstad.com/archive/1/)",
        )

    def test_load_snapshot_file_requires_split_body_file(self):
        original_repo = content.REPO
        try:
            with tempfile.TemporaryDirectory() as tmp:
                root = Path(tmp)
                metadata = root / "data" / "buttondown" / "emails" / "1.json"
                metadata.parent.mkdir(parents=True)
                metadata.write_text(
                    json.dumps(
                        {
                            "id": "em_1",
                            "number": 1,
                            "subject": "Weekly Thing 1",
                            "body_path": "data/buttondown/bodies/1.md",
                        }
                    ),
                    encoding="utf-8",
                )
                content.REPO = root

                with self.assertRaisesRegex(RuntimeError, "missing raw body file"):
                    content.load_snapshot_file(metadata)
        finally:
            content.REPO = original_repo

    def test_derive_issue_number_prefers_numeric_slug(self):
        self.assertEqual(
            content.derive_issue_number(
                {
                    "slug": "345",
                    "subject": "Weekly Thing 999 / Mistyped Subject",
                }
            ),
            345,
        )

    def test_changed_fields_reports_only_local_differences(self):
        snapshot = {
            "body": "Original",
            "subject": "Weekly Thing 1",
            "description": "Old",
            "image": "",
            "slug": "1",
        }
        local = {
            "body": "Original",
            "subject": "Weekly Thing 1",
            "description": "New",
            "image": "",
            "slug": "1",
        }

        self.assertEqual(content.changed_fields(snapshot, local), {"description": "New"})

    def test_classify_push_fields_detects_remote_conflict(self):
        snapshot = {"body": "Original", "description": "Old"}
        local = {"body": "Local", "description": "New"}
        live = {"body": "Remote", "description": "Old"}

        safe, conflicts = content.classify_push_fields(snapshot, local, live)

        self.assertEqual(safe, {"description": "New"})
        self.assertEqual(conflicts, ["body"])

    def test_classify_push_fields_force_includes_conflicts(self):
        snapshot = {"body": "Original"}
        local = {"body": "Local"}
        live = {"body": "Remote"}

        safe, conflicts = content.classify_push_fields(snapshot, local, live, force=True)

        self.assertEqual(safe, {"body": "Local"})
        self.assertEqual(conflicts, ["body"])


if __name__ == "__main__":
    unittest.main()
