import re
import sys
import unittest
from pathlib import Path

import yaml


REPO = Path(__file__).resolve().parents[1]
AUDIO = REPO / "pipeline" / "audio"
sys.path.insert(0, str(AUDIO))

import script as audio_script  # noqa: E402  (path-extended import)


def archive_fixture(issue):
    raw = (REPO / "apps" / "site" / "archive" / f"{issue}.md").read_text(encoding="utf-8")
    match = re.match(r"^---\n(.+?)\n---\n(.*)", raw, re.DOTALL)
    frontmatter = yaml.safe_load(match.group(1))
    # Strip whichever generated-notice prefix the archive file carries —
    # current (from data/issues) plus the two legacy variants in git history.
    body = re.sub(
        r"^<!-- Generated by (?:scripts/content|pipeline/content/content)\.py "
        r"from data/(?:buttondown|issues); do not edit directly\. -->\n",
        "",
        match.group(2),
    )
    return frontmatter, body


class AudioScriptTests(unittest.TestCase):
    def test_tinyletter_issue_gets_preamble_and_plain_links(self):
        frontmatter, body = archive_fixture(1)
        rendered = audio_script.body_to_audio_script(body, frontmatter)

        self.assertIn("The Weekly Thing, issue 1.", rendered)
        self.assertIn("Published May 13, twenty seventeen.", rendered)
        self.assertNotIn("https://", rendered)

    def test_mailchimp_emoji_headings_become_spoken_cues(self):
        frontmatter, body = archive_fixture(107)
        rendered = audio_script.body_to_audio_script(body, frontmatter)

        self.assertIn("Now, the Featured Links section.", rendered)
        self.assertIn("Now, the Notable Links section.", rendered)
        self.assertIn("Now, more links.", rendered)
        self.assertNotIn("🏅", rendered)
        self.assertNotIn("📌", rendered)
        self.assertNotIn("🍞", rendered)

    def test_buttondown_link_cards_keep_title_only(self):
        frontmatter, body = archive_fixture(345)
        rendered = audio_script.body_to_audio_script(body, frontmatter)

        self.assertIn("OpenAI’s New Codex App Has the Best", rendered)
        self.assertNotIn("https://www.macstories.net", rendered)
        self.assertNotIn("buttondown-editor-mode", rendered)

    def test_cover_block_with_native_img_is_stripped(self):
        """Modern issues emit the cover as a native <img> tag rather
        than markdown ![alt](src). Neither the alt text, caption,
        date, nor location should appear in the spoken audio."""
        from script.common import strip_cover_blocks

        body = (
            "## Currently\n\nplaceholder\n\n"
            "---\n\n"
            '<img src="https://files.thingelstad.com/weekly-thing/349/cover.jpg" '
            'alt="Golden sunset over a calm lake with tree silhouettes." />\n\n'
            "Beautiful evening with the sun coming down.\n\n"
            "May 16, 2026  \n"
            "Cannon Lake, Warsaw, MN\n\n"
            "---\n\n"
            "## Journal\n\nJournal entry stays.\n"
        )
        stripped = strip_cover_blocks(body)
        self.assertNotIn("Golden sunset", stripped)
        self.assertNotIn("Beautiful evening", stripped)
        self.assertNotIn("Cannon Lake", stripped)
        self.assertNotIn("cover.jpg", stripped)
        # Surrounding sections survive.
        self.assertIn("## Currently", stripped)
        self.assertIn("## Journal", stripped)
        self.assertIn("Journal entry stays.", stripped)

    def test_cover_block_with_markdown_image_still_stripped(self):
        """Legacy issues used ![alt](src) for the cover. The regex
        must still match that form."""
        from script.common import strip_cover_blocks

        body = (
            "---\n\n"
            "![Old caption](https://example.com/cover.jpg)\n\n"
            "Caption line.\n\n"
            "Apr 1, 2020  \nMinneapolis, MN\n\n"
            "---\n\n"
            "## Notable\n\nLink one.\n"
        )
        stripped = strip_cover_blocks(body)
        self.assertNotIn("Old caption", stripped)
        self.assertNotIn("Caption line", stripped)
        self.assertNotIn("Minneapolis", stripped)
        self.assertIn("## Notable", stripped)

    def test_modern_link_sections_announce_total_and_index(self):
        # Before the first link in Notable/Briefly, listeners now hear
        # "There are N links this week." so they know how big the section
        # is. Each per-link cue then carries "Link X of N. \"Title\"" so
        # they always know where they are in the count.
        frontmatter = {
            "number": 349,  # > LEGACY_MAX_ISSUE → modern transform
            "subject": "Weekly Thing 349",
            "publish_date": "2026-05-23T12:00:00Z",
        }
        body = (
            "## Notable\n\n"
            "### [First link](https://example.com/1)\n\n"
            "First blurb.\n\n"
            "### [Second link](https://example.com/2)\n\n"
            "Second blurb.\n\n"
            "### [Third link](https://example.com/3)\n\n"
            "Third blurb.\n\n"
            "## Briefly\n\n"
            "Briefly commentary → **[Quick read](https://example.com/q)**\n\n"
            "More commentary → **[Another read](https://example.com/r)**\n"
        )
        rendered = audio_script.body_to_audio_script(body, frontmatter)
        # Notable: three links → "There are three links this week." then
        # "Link one of three.", "Link two of three.", "Link three of three."
        self.assertIn("Now, the Notable section.", rendered)
        self.assertIn("There are three links this week.", rendered)
        self.assertIn('Link one of three. "First link"', rendered)
        self.assertIn('Link two of three. "Second link"', rendered)
        self.assertIn('Link three of three. "Third link"', rendered)
        # Briefly: two links → "There are two links this week." then
        # "Link one of two.", "Link two of two."
        self.assertIn("Now, the Briefly section.", rendered)
        self.assertIn("There are two links this week.", rendered)
        self.assertIn('Link one of two. "Quick read"', rendered)
        self.assertIn('Link two of two. "Another read"', rendered)
        # No pre-change "Link N." (without "of TOTAL") should leak through.
        self.assertNotIn('Link one. "', rendered)
        self.assertNotIn('Link two. "', rendered)

    def test_modern_single_link_section_uses_singular_count(self):
        frontmatter = {
            "number": 349,
            "subject": "Weekly Thing 349",
            "publish_date": "2026-05-23T12:00:00Z",
        }
        body = (
            "## Notable\n\n"
            "### [Only link](https://example.com/x)\n\n"
            "Just the one.\n"
        )
        rendered = audio_script.body_to_audio_script(body, frontmatter)
        self.assertIn("There is one link this week.", rendered)
        self.assertIn('Link one of one. "Only link"', rendered)

    def test_modern_empty_link_section_skips_count_sentence(self):
        # An empty link section is dropped from the audio entirely by
        # the shared finalize_script pass (it'd just be a heading intro
        # with nothing after it). The count-sentence change must NOT
        # leak a "There are zero links this week" line in its place.
        frontmatter = {
            "number": 349,
            "subject": "Weekly Thing 349",
            "publish_date": "2026-05-23T12:00:00Z",
        }
        body = (
            "## Notable\n\n"
            "## Briefly\n\n"
            "Some commentary → **[A link](https://example.com/x)**\n"
        )
        rendered = audio_script.body_to_audio_script(body, frontmatter)
        # Empty Notable section drops cleanly — no intro, no count line.
        self.assertNotIn("Now, the Notable section.", rendered)
        self.assertNotIn("zero links", rendered)
        # Briefly still announces its single link with the singular form.
        self.assertIn("There is one link this week.", rendered)
        self.assertIn('Link one of one. "A link"', rendered)

    def test_legacy_path_unchanged_by_count_addition(self):
        # The count-anchor change lives in modern.py only — legacy issues
        # (#1-130) route through legacy.py and should still announce
        # "Link N. \"Title\"" without the "of TOTAL" suffix.
        frontmatter, body = archive_fixture(107)
        rendered = audio_script.body_to_audio_script(body, frontmatter)
        # No "of TOTAL" cue anywhere in legacy output.
        self.assertNotIn(" of one. ", rendered)
        self.assertNotIn(" of two. ", rendered)
        self.assertNotIn("links this week", rendered)
        self.assertNotIn("link this week", rendered)

    def test_blockquotes_code_and_normalization(self):
        frontmatter = {
            "number": 999,
            "subject": "Weekly Thing 999 / Audio",
            "publish_date": "2026-04-26T12:00:00Z",
        }
        body = """<!-- hidden -->
![Alt text](https://example.com/image.jpg)
## Featured Links 🏅

> This is quoted text vs. normal text.
> It cost $12.50 on the 21st.

```python
print("skip me")
```

This is `inline code` with [a link](https://example.com), e.g. a test & sample.
"""
        rendered = audio_script.body_to_audio_script(body, frontmatter)

        self.assertIn("Quote.\nThis is quoted text versus normal text. It cost 12 dollars and 50 cents on the twenty first.\nEnd quote.", rendered)
        self.assertNotIn("skip me", rendered)
        self.assertIn("inline code with a link, for example a test and sample.", rendered)


if __name__ == "__main__":
    unittest.main()
