import importlib.util
import re
import sys
import unittest
from pathlib import Path

import yaml


REPO = Path(__file__).resolve().parents[1]
AUDIO = REPO / "pipeline" / "audio"
sys.path.insert(0, str(AUDIO))

spec = importlib.util.spec_from_file_location("audio_script", AUDIO / "script.py")
audio_script = importlib.util.module_from_spec(spec)
spec.loader.exec_module(audio_script)


def archive_fixture(issue):
    raw = (REPO / "apps" / "site" / "archive" / f"{issue}.md").read_text(encoding="utf-8")
    match = re.match(r"^---\n(.+?)\n---\n(.*)", raw, re.DOTALL)
    frontmatter = yaml.safe_load(match.group(1))
    body = re.sub(
        r"^<!-- Generated by (?:scripts/content|pipeline/content/content)\.py from data/buttondown; do not edit directly\. -->\n",
        "",
        match.group(2),
    )
    return frontmatter, body


class AudioScriptTests(unittest.TestCase):
    def test_tinyletter_issue_gets_preamble_and_plain_links(self):
        frontmatter, body = archive_fixture(1)
        rendered = audio_script.body_to_audio_script(body, frontmatter)

        self.assertIn("The Weekly Thing, issue 1.", rendered)
        self.assertIn("Published May 13, twenty seventeen.", rendered)
        self.assertNotIn("https://", rendered)

    def test_mailchimp_emoji_headings_become_spoken_cues(self):
        frontmatter, body = archive_fixture(107)
        rendered = audio_script.body_to_audio_script(body, frontmatter)

        self.assertIn("\n\nFeatured links.\n\n", rendered)
        self.assertIn("\n\nNotable links.\n\n", rendered)
        self.assertIn("\n\nYet more links.\n\n", rendered)
        self.assertNotIn("🏅", rendered)
        self.assertNotIn("📌", rendered)
        self.assertNotIn("🍞", rendered)

    def test_buttondown_link_cards_keep_title_only(self):
        frontmatter, body = archive_fixture(345)
        rendered = audio_script.body_to_audio_script(body, frontmatter)

        self.assertIn("OpenAI’s New Codex App Has the Best", rendered)
        self.assertNotIn("https://www.macstories.net", rendered)
        self.assertNotIn("buttondown-editor-mode", rendered)

    def test_blockquotes_code_and_normalization(self):
        frontmatter = {
            "number": 999,
            "subject": "Weekly Thing 999 / Audio",
            "publish_date": "2026-04-26T12:00:00Z",
        }
        body = """<!-- hidden -->
![Alt text](https://example.com/image.jpg)
## Featured Links 🏅

> This is quoted text vs. normal text.
> It cost $12.50 on the 21st.

```python
print("skip me")
```

This is `inline code` with [a link](https://example.com), e.g. a test & sample.
"""
        rendered = audio_script.body_to_audio_script(body, frontmatter)

        self.assertIn("\n\nThis is quoted text versus normal text. It cost 12 dollars and 50 cents on the twenty first.\n\n", rendered)
        self.assertNotIn("skip me", rendered)
        self.assertIn("inline code with a link, for example a test and sample.", rendered)


if __name__ == "__main__":
    unittest.main()
