import importlib.util
import tempfile
import unittest
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "scripts" / "build_librarian_corpus.py"

spec = importlib.util.spec_from_file_location("build_librarian_corpus", SCRIPT)
corpus = importlib.util.module_from_spec(spec)
spec.loader.exec_module(corpus)


class LibrarianCorpusTests(unittest.TestCase):
    def test_builds_chunks_with_issue_citations(self):
        with tempfile.TemporaryDirectory() as tmp:
            archive = Path(tmp)
            (archive / "1.md").write_text(
                "<!-- Generated by scripts/content.py from data/buttondown; do not edit directly. -->\n"
                "---\n"
                "number: 1\n"
                "subject: Weekly Thing 1\n"
                "publish_date: 2026-01-01T12:00:00Z\n"
                "---\n"
                "Intro paragraph.\n\n"
                "## Open Web\n\n"
                "RSS and personal websites are useful.\n",
                encoding="utf-8",
            )

            result = corpus.build_corpus(archive)

        self.assertEqual(result["issue_count"], 1)
        self.assertGreaterEqual(result["chunk_count"], 1)
        self.assertEqual(result["chunks"][0]["issue_number"], 1)
        self.assertEqual(result["chunks"][0]["url"], "/archive/1/")

    def test_rejects_template_leaks(self):
        with tempfile.TemporaryDirectory() as tmp:
            archive = Path(tmp)
            (archive / "1.md").write_text(
                "---\nnumber: 1\nsubject: Weekly Thing 1\n---\n"
                "Hello {{ subscriber.email }}\n",
                encoding="utf-8",
            )

            with self.assertRaisesRegex(RuntimeError, "Template/generated content leaked"):
                corpus.build_corpus(archive)


if __name__ == "__main__":
    unittest.main()
