#!/usr/bin/env python3
"""Per-issue pipeline state report.

For each issue, computes the current state at every pipeline stage:
Buttondown source, body file, archive front matter, audio, and the
deployed librarian corpus. Useful for ad-hoc reporting, agent review,
and powering /ops/ on the site.

Usage:
  python pipeline/status.py                 # human-readable table
  python pipeline/status.py --json PATH     # write JSON, no stdout table
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "pipeline" / "audio"))

from manifest import hash_text  # noqa: E402
from script import body_to_audio_script  # noqa: E402

ISSUES_ROOT = REPO / "data" / "issues"
AUDIO_MANIFEST = REPO / "data" / "audio" / "manifest.json"
ARCHIVE = REPO / "apps" / "site" / "archive"
LIBRARIAN_BUCKET = os.environ.get("LIBRARIAN_BUCKET", "weekly-thing-librarian")
LIBRARIAN_CORPUS_KEY = os.environ.get("LIBRARIAN_CORPUS_KEY", "artifacts/corpus.json")
LIBRARIAN_GRAPH_KEY = os.environ.get("LIBRARIAN_GRAPH_KEY", "artifacts/graph.json")

GENERATED_NOTICE_RE = "<!-- Generated by"


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def load_archive_frontmatter(path: Path) -> tuple[dict, str]:
    """Parse YAML front matter + body. Tolerant of the generated-notice line."""
    raw = path.read_text(encoding="utf-8")
    if not raw.startswith("---\n"):
        return {}, raw
    end = raw.find("\n---\n", 4)
    if end == -1:
        return {}, raw
    fm_text = raw[4:end]
    body = raw[end + 5 :]
    # strip the generated notice line if present
    body_lines = body.split("\n")
    while body_lines and (not body_lines[0].strip() or body_lines[0].startswith(GENERATED_NOTICE_RE)):
        body_lines.pop(0)
    body = "\n".join(body_lines)
    fm: dict = {}
    for line in fm_text.split("\n"):
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip().strip("'").strip('"')
        if key and val and not key.startswith(("-", " ")):
            fm[key] = val
    return fm, body


def body_has_local_edits(rel_path: str) -> bool:
    """True if the working-tree file differs from HEAD's blob."""
    try:
        result = subprocess.run(
            ["git", "diff", "--quiet", "HEAD", "--", rel_path],
            cwd=REPO, check=False, capture_output=True,
        )
        return result.returncode != 0
    except FileNotFoundError:
        return False


def s3_object_metadata(bucket: str, key: str) -> dict | None:
    try:
        import boto3
        from botocore.exceptions import ClientError, NoCredentialsError
    except ImportError:
        return None
    try:
        head = boto3.client("s3").head_object(Bucket=bucket, Key=key)
    except (ClientError, NoCredentialsError):
        return None
    metadata = {
        "size": head.get("ContentLength"),
        "last_modified": head.get("LastModified").isoformat().replace("+00:00", "Z") if head.get("LastModified") else None,
        "etag": head.get("ETag", "").strip('"'),
    }
    # The corpus is too big to download whole, but the top-level metadata
    # (embedding_model, embedding_dimensions, issue_count, chunk_count)
    # lives in the first ~200 bytes — readable with a Range GET. Best
    # effort; we keep the metadata even if the parse fails.
    if key.endswith("corpus.json"):
        try:
            head_bytes = boto3.client("s3").get_object(
                Bucket=bucket, Key=key, Range="bytes=0-2047"
            )["Body"].read()
            text = head_bytes.decode("utf-8", errors="ignore")
            for field in ("embedding_model", "embedding_dimensions", "issue_count", "chunk_count"):
                m = re.search(rf'"{field}"\s*:\s*("?)([^,"\n}}]+)\1', text)
                if m:
                    val = m.group(2)
                    if val.isdigit():
                        metadata[field] = int(val)
                    elif val == "null":
                        metadata[field] = None
                    else:
                        metadata[field] = val
        except (ClientError, NoCredentialsError, UnicodeDecodeError):
            pass
    return metadata


def collect_issues() -> list[dict]:
    """Walk every issue and compute per-stage state.

    After the workshop-as-source inversion, the issue universe is the set of
    numeric directories under data/issues/ — that's what the website builds
    from. The Buttondown-source column was removed; the body-edit signal now
    reflects edits to data/issues/{N}/archive.md, which is the editorial
    source of truth.
    """
    audio_manifest = {}
    if AUDIO_MANIFEST.exists():
        audio_manifest = json.loads(AUDIO_MANIFEST.read_text())

    # Numeric issue dirs in data/issues/ are first-class issues; bonus pages
    # like "140-special" aren't part of the per-issue pipeline contract.
    issue_numbers = sorted(
        {d.name for d in ISSUES_ROOT.iterdir() if d.is_dir() and d.name.isdigit()},
        key=lambda s: int(s),
    )
    archive_files = {p.stem: p for p in ARCHIVE.glob("*.md") if p.stem.isdigit()}

    rows: list[dict] = []
    for n in issue_numbers:
        body_rel = f"data/issues/{n}/archive.md"
        body_exists = (REPO / body_rel).exists()
        body_local_edits = body_has_local_edits(body_rel) if body_exists else False

        archive_path = archive_files.get(n)
        archive_exists = archive_path is not None
        archive_fm: dict = {}
        archive_body = ""
        if archive_exists:
            archive_fm, archive_body = load_archive_frontmatter(archive_path)

        # Audio state — what would render now vs. what's in manifest. For
        # Workshop-shipped issues with data/issues/{N}/transcript/, the
        # script reflects the per-block concatenation; for legacy issues
        # it's the modern.py / legacy.py transform output. body_to_audio_script
        # handles the legacy single-string path; we still hash the
        # apps/site/archive/{N}.md derivation as a quick freshness check.
        audio_entry = audio_manifest.get(n, {})
        current_script_hash = ""
        if archive_exists:
            try:
                script = body_to_audio_script(archive_body, archive_fm)
                current_script_hash = hash_text(script)
            except Exception:
                current_script_hash = "ERROR"

        manifest_script_hash = audio_entry.get("audio_script_hash", "")
        audio_in_manifest = bool(audio_entry)
        audio_out_of_date = audio_in_manifest and current_script_hash != "" and current_script_hash != manifest_script_hash

        rows.append({
            "number": int(n),
            "subject": archive_fm.get("subject", ""),
            "publish_date": archive_fm.get("publish_date", ""),
            "body": {
                "tracked": body_exists,
                "has_local_edits": body_local_edits,
            },
            "archive": {
                "exists": archive_exists,
                "word_count": int(archive_fm.get("word_count")) if archive_fm.get("word_count", "").isdigit() else None,
            },
            "audio": {
                "in_manifest": audio_in_manifest,
                "url": audio_entry.get("audio_url"),
                "duration_seconds": audio_entry.get("audio_duration_seconds"),
                "byte_size": audio_entry.get("byte_size"),
                "voice": audio_entry.get("audio_voice"),
                "rendered_at": audio_entry.get("generated_at"),
                "manifest_script_hash": manifest_script_hash,
                "current_script_hash": current_script_hash,
                "out_of_date": audio_out_of_date,
            },
        })
    return rows


def deployed_artifacts() -> dict:
    return {
        "corpus": s3_object_metadata(LIBRARIAN_BUCKET, LIBRARIAN_CORPUS_KEY) or {"unavailable": True},
        "graph":  s3_object_metadata(LIBRARIAN_BUCKET, LIBRARIAN_GRAPH_KEY) or {"unavailable": True},
    }


def build_report() -> dict:
    issues = collect_issues()
    deployed = deployed_artifacts()

    # Librarian staleness as a single global signal: is the most recent
    # archive change newer than the deployed corpus? Per-issue staleness
    # would need per-issue content hashes embedded in the deployed corpus;
    # not worth the plumbing yet.
    corpus_mtime_str = deployed["corpus"].get("last_modified")
    librarian_stale = None
    latest_archive_mtime_str = None
    archive_paths = [ARCHIVE / f"{r['number']}.md" for r in issues]
    archive_paths = [p for p in archive_paths if p.exists()]
    if archive_paths:
        latest_mtime = max(p.stat().st_mtime for p in archive_paths)
        latest_dt = datetime.fromtimestamp(latest_mtime, tz=timezone.utc).replace(microsecond=0)
        latest_archive_mtime_str = latest_dt.isoformat().replace("+00:00", "Z")
        if corpus_mtime_str:
            corpus_dt = datetime.fromisoformat(corpus_mtime_str.replace("Z", "+00:00"))
            librarian_stale = latest_dt > corpus_dt

    summary = {
        "total_issues": len(issues),
        "archive_local_edits": sum(1 for r in issues if r["body"]["has_local_edits"]),
        "archive_missing": sum(1 for r in issues if not r["archive"]["exists"]),
        "audio_rendered": sum(1 for r in issues if r["audio"]["in_manifest"]),
        "audio_out_of_date": sum(1 for r in issues if r["audio"]["out_of_date"]),
        "audio_missing": sum(1 for r in issues if not r["audio"]["in_manifest"]),
        "deployed_corpus_uploaded_at": corpus_mtime_str,
        "latest_archive_modified_at": latest_archive_mtime_str,
        "librarian_likely_stale": librarian_stale,
    }
    return {
        "generated_at": now_iso(),
        "summary": summary,
        "deployed": deployed,
        "issues": issues,
    }


def print_table(report: dict) -> None:
    s = report["summary"]
    print(f"Pipeline status — generated {report['generated_at']}")
    thingy_state = "STALE" if s.get("librarian_likely_stale") else ("ok" if s.get("librarian_likely_stale") is False else "?")
    print(f"  total: {s['total_issues']}  audio rendered: {s['audio_rendered']}  audio stale: {s['audio_out_of_date']}  audio missing: {s['audio_missing']}  archive edits: {s['archive_local_edits']}  thingy: {thingy_state}")
    if s.get("deployed_corpus_uploaded_at"):
        print(f"  deployed corpus uploaded: {s['deployed_corpus_uploaded_at']}  latest archive change: {s.get('latest_archive_modified_at')}")
    print()
    print(f"  {'#':>4}  {'date':10}  {'audio':>5}  {'stale':5}  {'body':4}  subject")
    print(f"  {'-'*4}  {'-'*10}  {'-'*5}  {'-'*5}  {'-'*4}  {'-'*40}")
    for row in report["issues"]:
        date = (row["publish_date"] or "")[:10]
        audio = "✓" if row["audio"]["in_manifest"] else "—"
        stale = "STALE" if row["audio"]["out_of_date"] else ("—" if not row["audio"]["in_manifest"] else "ok")
        body = "EDIT" if row["body"]["has_local_edits"] else "ok"
        subj = (row["subject"] or "")[:60]
        print(f"  {row['number']:>4}  {date:10}  {audio:>5}  {stale:5}  {body:4}  {subj}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json", help="Write JSON report to this path. If omitted, prints a human table.")
    args = ap.parse_args()

    report = build_report()

    if args.json:
        out = Path(args.json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"Wrote pipeline status report to {out.relative_to(REPO) if out.is_relative_to(REPO) else out}", flush=True)
    else:
        print_table(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
