"""Build a citation-ready corpus for the archive librarian."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
import re
from pathlib import Path
from typing import Any

import boto3
import yaml
from dotenv import load_dotenv


REPO = Path(__file__).resolve().parents[2]
ARCHIVE_DIR = REPO / "site" / "archive"
OUT_PATH = REPO / "data" / "librarian" / "corpus.json"
DEFAULT_EMBEDDING_MODEL = "cohere.embed-english-v3"
DEFAULT_EMBEDDING_DIMENSIONS = 1024
COHERE_EMBED_MAX_TEXT_CHARS = 2048
GENERATED_NOTICE_RE = re.compile(r"^<!-- Generated by (?:scripts/content|pipeline/content/content)\.py.*?-->\s*", re.S)
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?", re.S)
TEMPLATE_LEAK_RE = re.compile(r"({%\s*|{{\s*|buttondown-editor-mode|Generated by (?:scripts/content|pipeline/content/content)\.py)", re.I)
HEADING_RE = re.compile(r"^(#{1,4})\s+(.+?)\s*$", re.M)
WORD_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9'\-]*")
SENTENCE_RE = re.compile(r"(?<=[.!?])\s+")
TOPIC_KEYWORDS = {
    "AI and agents": {"ai", "agent", "agents", "openai", "claude", "llm", "gpt", "model", "models", "prompt"},
    "Open web and RSS": {"rss", "feed", "feeds", "blog", "blogs", "website", "web", "podcast", "tapestry"},
    "Privacy and security": {"privacy", "security", "secure", "token", "tokens", "password", "surveillance", "encryption"},
    "Productivity and systems": {"productivity", "omnifocus", "gtd", "workflow", "calendar", "tasks", "method"},
    "IndieWeb and personal sites": {"indieweb", "microblog", "activitypub", "fediverse", "ownyourdata"},
    "Travel and place": {"travel", "banff", "lake", "trip", "hotel", "museum", "landscape", "airport", "europe", "city"},
    "Media and culture": {"book", "books", "movie", "film", "music", "media", "culture", "streaming", "podcast"},
    "Software development": {"software", "code", "developer", "development", "github", "api", "programming", "server"},
    "Crypto and web3": {"bitcoin", "crypto", "ethereum", "nft", "poap", "token", "tokens", "wallet", "web3"},
}
EVERGREEN_SECTIONS = {"essay", "journal", "issue", "briefly", "currently"}


def issue_sort_key(value: Any) -> tuple[int, str]:
    text = str(value)
    match = re.match(r"(\d+)", text)
    if not match:
        return (10**9, text)
    return (int(match.group(1)), text)


def read_issue(path: Path) -> tuple[dict[str, Any], str]:
    text = path.read_text(encoding="utf-8")
    text = GENERATED_NOTICE_RE.sub("", text)
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise RuntimeError(f"{path} is missing YAML front matter")
    metadata = yaml.safe_load(match.group(1)) or {}
    body = GENERATED_NOTICE_RE.sub("", text[match.end() :]).strip()
    return metadata, body


def clean_heading(value: str) -> str:
    value = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", value)
    value = re.sub(r"[*_`#]+", "", value)
    return " ".join(value.split())


def split_sections(body: str) -> list[tuple[str, str]]:
    matches = list(HEADING_RE.finditer(body))
    if not matches:
        return [("Issue", body.strip())]

    sections: list[tuple[str, str]] = []
    if matches[0].start() > 0:
        intro = body[: matches[0].start()].strip()
        if intro:
            sections.append(("Issue", intro))

    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(body)
        section_body = body[start:end].strip()
        if section_body:
            sections.append((clean_heading(match.group(2)), section_body))
    return sections


def words(text: str) -> list[str]:
    return WORD_RE.findall(text)


def body_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def parse_year(value: str) -> int | None:
    match = re.match(r"(\d{4})", str(value or ""))
    return int(match.group(1)) if match else None


def plain_text(markdown: str) -> str:
    text = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", markdown)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.M)
    text = re.sub(r"[*_>~]+", "", text)
    return " ".join(text.split())


def summarize_text(text: str, max_chars: int = 420) -> str:
    clean = plain_text(text)
    if len(clean) <= max_chars:
        return clean
    sentences = SENTENCE_RE.split(clean)
    summary = ""
    for sentence in sentences:
        if len(summary) + len(sentence) + 1 > max_chars:
            break
        summary = f"{summary} {sentence}".strip()
    return summary or clean[:max_chars].rsplit(" ", 1)[0]


def detect_topics(subject: str, body: str, limit: int = 6) -> list[str]:
    tokens = [token.lower() for token in words(f"{subject} {body[:12000]}")]
    counts = {}
    token_set = set(tokens)
    for topic, keywords in TOPIC_KEYWORDS.items():
        score = sum(tokens.count(keyword) for keyword in keywords if keyword in token_set)
        minimum = 1 if topic in {"AI and agents", "Open web and RSS"} else 2
        if score >= minimum:
            counts[topic] = score
    return [topic for topic, _ in sorted(counts.items(), key=lambda item: (-item[1], item[0]))[:limit]]


def content_kind(section: str) -> str:
    name = section.lower()
    if any(part in name for part in ("journal", "photo", "currently")):
        return "personal"
    if any(part in name for part in ("links", "briefly", "fortune")):
        return "links"
    if any(part in name for part in ("give back", "promotion", "sponsor")):
        return "meta"
    return "essay" if name in EVERGREEN_SECTIONS or len(name.split()) <= 4 else "reference"


def time_sensitivity(subject: str, body: str) -> str:
    text = f"{subject} {body[:4000]}".lower()
    if any(term in text for term in ("today", "this week", "beta", "launch", "announced", "now available")):
        return "time_sensitive"
    if any(term in text for term in ("principle", "framework", "lesson", "why", "how to")):
        return "evergreen"
    return "mixed"


def key_points_for_sections(sections: list[tuple[str, str]], limit: int = 5) -> list[str]:
    points = []
    for section, section_body in sections:
        if section.lower() in {"issue", "promotion", "give back"}:
            continue
        point = summarize_text(section_body, max_chars=180)
        if point:
            points.append(f"{section}: {point}")
        if len(points) == limit:
            break
    return points


def chunk_section(text: str, max_words: int = 260, overlap_words: int = 40) -> list[str]:
    tokens = words(text)
    if len(tokens) <= max_words:
        return [text.strip()] if text.strip() else []

    paragraphs = [p.strip() for p in re.split(r"\n{2,}", text) if p.strip()]
    chunks: list[str] = []
    current: list[str] = []
    current_words = 0

    for paragraph in paragraphs:
        count = len(words(paragraph))
        if current and current_words + count > max_words:
            chunks.append("\n\n".join(current).strip())
            overlap = " ".join(words(chunks[-1])[-overlap_words:])
            current = [overlap, paragraph] if overlap else [paragraph]
            current_words = len(words(overlap)) + count
        else:
            current.append(paragraph)
            current_words += count

    if current:
        chunks.append("\n\n".join(current).strip())
    return chunks


def chunk_id(issue_number: Any, section: str, index: int, text: str) -> str:
    digest = hashlib.sha256(f"{issue_number}\0{section}\0{index}\0{text}".encode("utf-8")).hexdigest()
    return digest[:16]


def build_corpus(archive_dir: Path = ARCHIVE_DIR, include_issue_bodies: bool = False) -> dict[str, Any]:
    chunks: list[dict[str, Any]] = []
    issues = []
    links: list[dict[str, Any]] = []
    topic_index: dict[str, dict[str, Any]] = {}
    for path in sorted(archive_dir.glob("*.md"), key=lambda p: issue_sort_key(p.stem)):
        metadata, body = read_issue(path)
        number = metadata.get("number") or path.stem
        subject = metadata.get("subject") or f"Weekly Thing {number}"
        publish_date = metadata.get("publish_date") or ""
        url = f"/archive/{number}/"
        issue_word_count = len(words(body))
        sections = split_sections(body)
        topics = detect_topics(subject, body)
        issue_summary = {
            "abstract": summarize_text(body),
            "key_points": key_points_for_sections(sections),
            "topics": topics,
            "time_sensitivity": time_sensitivity(subject, body),
        }
        issue_sections = [
            {"name": section, "text": section_body, "word_count": len(words(section_body))}
            for section, section_body in sections
        ]
        issue_links = []
        for link in metadata.get("links") or []:
            if not isinstance(link, dict):
                continue
            record = {
                "issue_number": number,
                "subject": subject,
                "publish_date": publish_date,
                "issue_year": parse_year(publish_date),
                "issue_url": url,
                "section": link.get("section"),
                "url": link.get("url"),
                "domain": link.get("domain"),
                "text": link.get("text") or link.get("title") or link.get("heading_context"),
                "heading_context": link.get("heading_context"),
                "context": link.get("context") or link.get("heading_context"),
            }
            if include_issue_bodies:
                issue_links.append(record)
                links.append(record)
        issues.append(
            {
                "number": number,
                "subject": subject,
                "publish_date": publish_date,
                "issue_year": parse_year(publish_date),
                "url": url,
                "word_count": issue_word_count,
                "body_hash": body_hash(body),
                "summary": issue_summary,
                "topics": topics,
            }
        )
        if include_issue_bodies:
            issues[-1]["body"] = body
            issues[-1]["sections"] = issue_sections
            issues[-1]["domains"] = metadata.get("domains") or []
            issues[-1]["links"] = issue_links
        for topic in topics:
            entry = topic_index.setdefault(
                topic,
                {
                    "name": topic,
                    "description": f"Archive material related to {topic.lower()}.",
                    "first_seen": publish_date,
                    "last_seen": publish_date,
                    "issue_numbers": [],
                    "representative_issues": [],
                    "related_topics": [],
                },
            )
            entry["issue_numbers"].append(number)
            if publish_date and (not entry["first_seen"] or publish_date < entry["first_seen"]):
                entry["first_seen"] = publish_date
            if publish_date and publish_date > entry["last_seen"]:
                entry["last_seen"] = publish_date

        for section, section_body in sections:
            for index, chunk_text in enumerate(chunk_section(section_body)):
                if TEMPLATE_LEAK_RE.search(chunk_text):
                    raise RuntimeError(f"Template/generated content leaked into corpus for issue {number}")
                chunks.append(
                    {
                        "id": chunk_id(number, section, index, chunk_text),
                        "issue_number": number,
                        "subject": subject,
                        "publish_date": publish_date,
                        "issue_year": parse_year(publish_date),
                        "url": url,
                        "section": section,
                        "text": chunk_text,
                        "word_count": len(words(chunk_text)),
                        "content_kind": content_kind(section),
                        "topics": topics,
                        "source_kind": "chunk",
                    }
                )

    for entry in topic_index.values():
        entry["representative_issues"] = entry["issue_numbers"][-8:]
        related = set()
        for issue in issues:
            if entry["name"] in issue.get("topics", []):
                related.update(topic for topic in issue.get("topics", []) if topic != entry["name"])
        entry["related_topics"] = sorted(related)[:8]

    return {
        "version": 2,
        "source": "site/archive",
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "embedding_model": None,
        "issue_count": len(issues),
        "chunk_count": len(chunks),
        "link_count": len(links),
        "issues": issues,
        "topics": sorted(topic_index.values(), key=lambda item: item["name"]),
        "links": links,
        "chunks": chunks,
    }


def fetch_bedrock_embeddings(inputs: list[str], model: str, input_type: str = "search_document") -> list[list[float]]:
    inputs = [text[:COHERE_EMBED_MAX_TEXT_CHARS] for text in inputs]
    response = boto3.client("bedrock-runtime").invoke_model(
        modelId=model,
        body=json.dumps({"texts": inputs, "input_type": input_type, "truncate": "END"}),
        accept="application/json",
        contentType="application/json",
    )
    data = json.loads(response["body"].read())
    embeddings = data.get("embeddings") or []
    if len(embeddings) != len(inputs):
        raise RuntimeError(f"Bedrock returned {len(embeddings)} embeddings for {len(inputs)} inputs")
    return embeddings


def add_bedrock_embeddings(corpus: dict[str, Any], model: str, dimensions: int, batch_size: int = 96) -> None:
    load_dotenv()
    chunks = corpus["chunks"]
    for start in range(0, len(chunks), batch_size):
        batch = chunks[start : start + batch_size]
        inputs = [
            "\n".join(
                [
                    f"Weekly Thing #{chunk['issue_number']}: {chunk['subject']}",
                    f"Section: {chunk['section']}",
                    f"Topics: {', '.join(chunk.get('topics', []))}",
                    chunk["text"],
                ]
                )
            for chunk in batch
        ]
        embeddings = fetch_bedrock_embeddings(inputs, model)
        for chunk, embedding in zip(batch, embeddings):
            chunk["embedding"] = embedding
        print(f"Embedded chunks {start + 1}-{start + len(batch)} of {len(chunks)}")
    corpus["embedding_model"] = model
    corpus["embedding_dimensions"] = len(chunks[0]["embedding"]) if chunks else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(OUT_PATH), help="Output JSON path")
    parser.add_argument("--embed", action="store_true", help="Add Bedrock Cohere embeddings to each chunk")
    parser.add_argument("--include-issue-bodies", action="store_true", help="Include full issue bodies and sections for runtime tools")
    parser.add_argument("--embedding-model", default=DEFAULT_EMBEDDING_MODEL)
    parser.add_argument("--embedding-dimensions", type=int, default=DEFAULT_EMBEDDING_DIMENSIONS)
    args = parser.parse_args()

    corpus = build_corpus(include_issue_bodies=args.include_issue_bodies)
    if args.embed:
        add_bedrock_embeddings(corpus, args.embedding_model, args.embedding_dimensions)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(corpus, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {corpus['chunk_count']} chunks from {corpus['issue_count']} issues to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
