"""Build a citation-ready corpus for the archive librarian.

Reads ``apps/site/archive/*.md``, splits each issue into chunks with topic/section
metadata, and (optionally) calls Bedrock Cohere to embed every chunk. The
resulting dict is JSON-serializable and is consumed by Thingy, the workshop
bot, and the graph builder.
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import boto3
import yaml
from dotenv import load_dotenv

from .paths import ARCHIVE_DIR, BLOG_DIR, FAQ_PATH, SITE_DIR


DEFAULT_EMBEDDING_MODEL = "cohere.embed-english-v3"
DEFAULT_EMBEDDING_DIMENSIONS = 1024
COHERE_EMBED_MAX_TEXT_CHARS = 2048
GENERATED_NOTICE_RE = re.compile(r"^<!-- Generated by (?:scripts/content|pipeline/content/content)\.py.*?-->\s*", re.S)
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?", re.S)
TEMPLATE_LEAK_RE = re.compile(r"({%\s*|{{\s*|buttondown-editor-mode|Generated by (?:scripts/content|pipeline/content/content)\.py)", re.I)
HEADING_RE = re.compile(r"^(#{1,4})\s+(.+?)\s*$", re.M)
WORD_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9'\-]*")
SENTENCE_RE = re.compile(r"(?<=[.!?])\s+")
TOPIC_KEYWORDS = {
    "AI and agents": {"ai", "agent", "agents", "openai", "claude", "llm", "gpt", "model", "models", "prompt"},
    "Open web and RSS": {"rss", "feed", "feeds", "blog", "blogs", "website", "web", "podcast", "tapestry"},
    "Privacy and security": {"privacy", "security", "secure", "token", "tokens", "password", "surveillance", "encryption"},
    "Productivity and systems": {"productivity", "omnifocus", "gtd", "workflow", "calendar", "tasks", "method"},
    "IndieWeb and personal sites": {"indieweb", "microblog", "activitypub", "fediverse", "ownyourdata"},
    "Travel and place": {"travel", "banff", "lake", "trip", "hotel", "museum", "landscape", "airport", "europe", "city"},
    "Media and culture": {"book", "books", "movie", "film", "music", "media", "culture", "streaming", "podcast"},
    "Software development": {"software", "code", "developer", "development", "github", "api", "programming", "server"},
    "Crypto and web3": {"bitcoin", "crypto", "ethereum", "nft", "poap", "token", "tokens", "wallet", "web3"},
}
EVERGREEN_SECTIONS = {"essay", "journal", "issue", "briefly", "currently"}


def issue_sort_key(value: Any) -> tuple[int, str]:
    text = str(value)
    match = re.match(r"(\d+)", text)
    if not match:
        return (10**9, text)
    return (int(match.group(1)), text)


def read_issue(path: Path) -> tuple[dict[str, Any], str]:
    text = path.read_text(encoding="utf-8")
    text = GENERATED_NOTICE_RE.sub("", text)
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise RuntimeError(f"{path} is missing YAML front matter")
    metadata = yaml.safe_load(match.group(1)) or {}
    body = GENERATED_NOTICE_RE.sub("", text[match.end() :]).strip()
    return metadata, body


def clean_heading(value: str) -> str:
    value = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", value)
    value = re.sub(r"[*_`#]+", "", value)
    return " ".join(value.split())


def split_sections(body: str) -> list[tuple[str, str]]:
    matches = list(HEADING_RE.finditer(body))
    if not matches:
        return [("Issue", body.strip())]

    sections: list[tuple[str, str]] = []
    if matches[0].start() > 0:
        intro = body[: matches[0].start()].strip()
        if intro:
            sections.append(("Issue", intro))

    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(body)
        section_body = body[start:end].strip()
        if section_body:
            sections.append((clean_heading(match.group(2)), section_body))
    return sections


def words(text: str) -> list[str]:
    return WORD_RE.findall(text)


def body_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def parse_year(value: str) -> int | None:
    match = re.match(r"(\d{4})", str(value or ""))
    return int(match.group(1)) if match else None


def plain_text(markdown: str) -> str:
    text = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", markdown)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.M)
    text = re.sub(r"[*_>~]+", "", text)
    return " ".join(text.split())


def summarize_text(text: str, max_chars: int = 420) -> str:
    clean = plain_text(text)
    if len(clean) <= max_chars:
        return clean
    sentences = SENTENCE_RE.split(clean)
    summary = ""
    for sentence in sentences:
        if len(summary) + len(sentence) + 1 > max_chars:
            break
        summary = f"{summary} {sentence}".strip()
    return summary or clean[:max_chars].rsplit(" ", 1)[0]


def detect_topics(subject: str, body: str, limit: int = 6) -> list[str]:
    tokens = [token.lower() for token in words(f"{subject} {body[:12000]}")]
    counts = {}
    token_set = set(tokens)
    for topic, keywords in TOPIC_KEYWORDS.items():
        score = sum(tokens.count(keyword) for keyword in keywords if keyword in token_set)
        minimum = 1 if topic in {"AI and agents", "Open web and RSS"} else 2
        if score >= minimum:
            counts[topic] = score
    return [topic for topic, _ in sorted(counts.items(), key=lambda item: (-item[1], item[0]))[:limit]]


def content_kind(section: str) -> str:
    name = section.lower()
    if any(part in name for part in ("journal", "photo", "currently")):
        return "personal"
    if any(part in name for part in ("links", "briefly", "fortune")):
        return "links"
    if any(part in name for part in ("give back", "promotion", "sponsor")):
        return "meta"
    return "essay" if name in EVERGREEN_SECTIONS or len(name.split()) <= 4 else "reference"


def time_sensitivity(subject: str, body: str) -> str:
    text = f"{subject} {body[:4000]}".lower()
    if any(term in text for term in ("today", "this week", "beta", "launch", "announced", "now available")):
        return "time_sensitive"
    if any(term in text for term in ("principle", "framework", "lesson", "why", "how to")):
        return "evergreen"
    return "mixed"


def key_points_for_sections(sections: list[tuple[str, str]], limit: int = 5) -> list[str]:
    points = []
    for section, section_body in sections:
        if section.lower() in {"issue", "promotion", "give back"}:
            continue
        point = summarize_text(section_body, max_chars=180)
        if point:
            points.append(f"{section}: {point}")
        if len(points) == limit:
            break
    return points


def chunk_section(text: str, max_words: int = 260, overlap_words: int = 40) -> list[str]:
    tokens = words(text)
    if len(tokens) <= max_words:
        return [text.strip()] if text.strip() else []

    paragraphs = [p.strip() for p in re.split(r"\n{2,}", text) if p.strip()]
    chunks: list[str] = []
    current: list[str] = []
    current_words = 0

    for paragraph in paragraphs:
        count = len(words(paragraph))
        if current and current_words + count > max_words:
            chunks.append("\n\n".join(current).strip())
            overlap = " ".join(words(chunks[-1])[-overlap_words:])
            current = [overlap, paragraph] if overlap else [paragraph]
            current_words = len(words(overlap)) + count
        else:
            current.append(paragraph)
            current_words += count

    if current:
        chunks.append("\n\n".join(current).strip())
    return chunks


# --- non-archive sources -------------------------------------------------
#
# Thingy's questions aren't all "what did you say about X in issue N?".
# Origin / cadence / "what's the supporting membership" / FAQ-shaped
# questions land just as often. The archive corpus didn't carry any of
# that, so Thingy would guess. We bring three structured site sources
# into the same embedded corpus alongside issue chunks so semantic
# retrieval surfaces them naturally:
#
#   - apps/site/about.njk           → site:about           page-prose chunks
#   - apps/site/support.njk         → site:members         page-prose chunks
#   - apps/site/_data/support.json  → site:nonprofit-history structured-fact chunk
#   - apps/librarian/lambda/shared/faq.json → faq:<section>:<index> chunks
#
# **Privacy fence:** these chunks must never carry subscriber/member
# counts. The site renders ``stats.premium_subscriber_count`` on
# /members/, but we deliberately don't read ``_data/stats.json`` or
# ``_data/supportTotals.js`` here, and a unit test scans the final
# corpus to confirm no count field leaked in (would fail loud if a
# future njk template change embedded a subscriber count directly
# into about.njk / support.njk).

# Banned strings that must not appear anywhere in the corpus chunks.
# subscriber_count + premium_subscriber_count are stats.json field names;
# matching them anywhere catches the obvious "we accidentally rendered
# the stats block into the page" regression.
CORPUS_PRIVACY_DENYLIST: tuple[str, ...] = (
    "subscriber_count",
    "premium_subscriber_count",
    "stats.subscriber",
    "stats.premium",
)

_FRONTMATTER_FENCE_RE = re.compile(r"\A---\s*\n.*?\n---\s*\n", re.S)
_NJK_BLOCK_RE = re.compile(r"\{%.*?%\}", re.S)
_NJK_EXPR_RE = re.compile(r"\{\{(.*?)\}\}", re.S)
_HTML_TAG_RE = re.compile(r"<[^>]+>")
_HTML_ENTITY_MAP = {
    "&mdash;": "—", "&ndash;": "–", "&hellip;": "…",
    "&lsquo;": "'", "&rsquo;": "'", "&ldquo;": '"', "&rdquo;": '"',
    "&amp;": "&", "&nbsp;": " ", "&middot;": "·",
    "&rarr;": "→",
}


def _resolve_njk_expr(raw: str, replacements: dict[str, str]) -> str:
    """Best-effort resolution of a ``{{ var | filter }}`` expression.
    Returns the matched replacement if the variable name is in
    ``replacements``; otherwise returns ``""`` so the surrounding prose
    reads cleanly without template debris.
    """
    bare = raw.split("|", 1)[0].strip()
    return replacements.get(bare, "")


def _strip_njk_page(text: str, *, replacements: dict[str, str] | None = None) -> str:
    """Reduce a Nunjucks template (frontmatter + HTML + ``{% %}`` /
    ``{{ }}`` syntax) to plain prose suitable for embedding.

    Frontmatter is dropped wholesale. ``{% %}`` control-flow tags are
    deleted (their bodies stay — control flow doesn't change the visible
    text for these pages). ``{{ expr }}`` expressions are resolved via
    ``replacements`` if known (e.g. ``yearlyPrice → "48"``) and dropped
    otherwise. HTML tags get stripped; basic entities decoded; whitespace
    normalized.
    """
    replacements = replacements or {}
    s = _FRONTMATTER_FENCE_RE.sub("", text or "")
    s = _NJK_BLOCK_RE.sub("", s)
    s = _NJK_EXPR_RE.sub(lambda m: _resolve_njk_expr(m.group(1), replacements), s)
    # Strip inline <script>…</script> + <style>…</style> blocks before
    # tag-stripping so their bodies don't leak into the text.
    s = re.sub(r"<(script|style)\b[^>]*>.*?</\1>", "", s, flags=re.I | re.S)
    s = _HTML_TAG_RE.sub(" ", s)
    for entity, decoded in _HTML_ENTITY_MAP.items():
        s = s.replace(entity, decoded)
    s = re.sub(r"&#x?\d+;", "", s)
    # Collapse runs of whitespace to single spaces, then re-introduce
    # paragraph breaks where the source had blank lines.
    s = re.sub(r"[ \t]+", " ", s)
    s = re.sub(r"\n\s*\n+", "\n\n", s)
    s = re.sub(r"^[ \t]+|[ \t]+$", "", s, flags=re.M)
    return s.strip()


def _site_page_chunks(
    *,
    site_dir: Path,
    issue_count: int,
    years_active: int,
    latest_issue_number: Any,
) -> list[dict[str, Any]]:
    """Build site_page chunks for /about/ + /members/ from the .njk
    templates and the structured support.json data.

    Each chunk lands with ``source_kind: "site_page"``, no
    ``issue_number`` (these aren't issues), and a stable id like
    ``site:about:0`` so the embedded corpus is reproducible across
    builds (same input → same id → cache hit on the deploy reupload).
    """
    out: list[dict[str, Any]] = []
    replacements = {
        "archiveStats.yearsActive": str(years_active),
        "collections.issuesByDate[0].data.number": str(latest_issue_number or ""),
        "issueCount": str(issue_count),
        "yearsActive": str(years_active),
        "support.yearly_price": "",  # filled in members loader below
    }

    about_path = site_dir / "about.njk"
    if about_path.exists():
        prose = _strip_njk_page(about_path.read_text(encoding="utf-8"), replacements=replacements)
        for index, chunk_text in enumerate(chunk_section(prose)):
            out.append({
                "id": f"site:about:{index}",
                "issue_number": None,
                "subject": "About the Weekly Thing",
                "publish_date": None,
                "issue_year": None,
                "url": "/about/",
                "section": "About",
                "text": chunk_text,
                "word_count": len(words(chunk_text)),
                "content_kind": "site_page",
                "topics": [],
                "source_kind": "site_page",
            })

    support_data_path = site_dir / "_data" / "support.json"
    support_data: dict[str, Any] = {}
    if support_data_path.exists():
        try:
            support_data = json.loads(support_data_path.read_text(encoding="utf-8"))
        except (ValueError, TypeError):
            support_data = {}
    yearly_price = support_data.get("yearly_price") or 48
    replacements["support.yearly_price"] = str(yearly_price)

    members_path = site_dir / "support.njk"
    if members_path.exists():
        prose = _strip_njk_page(members_path.read_text(encoding="utf-8"), replacements=replacements)
        for index, chunk_text in enumerate(chunk_section(prose)):
            out.append({
                "id": f"site:members:{index}",
                "issue_number": None,
                "subject": "Supporting Membership",
                "publish_date": None,
                "issue_year": None,
                "url": "/members/",
                "section": "Supporting Membership",
                "text": chunk_text,
                "word_count": len(words(chunk_text)),
                "content_kind": "site_page",
                "topics": [],
                "source_kind": "site_page",
            })

    # Render the structured nonprofit history into its own chunk —
    # concrete, year-by-year, easy for Thingy to quote.
    if support_data:
        history_parts: list[str] = []
        current = support_data.get("current") or {}
        if current.get("nonprofit"):
            history_parts.append(
                f"The {current.get('year_label') or current.get('year') or 'current'} "
                f"Supporting Member nonprofit is {current['nonprofit']}"
                + (f" — {current['description']}" if current.get("description") else "")
                + "."
            )
        past = support_data.get("past") or []
        if past:
            history_parts.append("Past nonprofits supported by Weekly Thing Supporting Members:")
            for org in past:
                if not isinstance(org, dict):
                    continue
                year_label = org.get("year_label") or org.get("year")
                name = org.get("nonprofit") or org.get("short_name")
                if not name:
                    continue
                amount = org.get("amount_raised")
                amount_str = f" (~${amount:,.0f} raised)" if isinstance(amount, (int, float)) else ""
                history_parts.append(f"- {year_label}: {name}{amount_str}")
        if history_parts:
            text = "\n".join(history_parts)
            out.append({
                "id": "site:nonprofit-history:0",
                "issue_number": None,
                "subject": "Supporting Member nonprofit history",
                "publish_date": None,
                "issue_year": None,
                "url": "/members/",
                "section": "Supporting Member nonprofit history",
                "text": text,
                "word_count": len(words(text)),
                "content_kind": "site_page",
                "topics": [],
                "source_kind": "site_page",
            })

    return out


def _faq_chunks(*, faq_path: Path, issue_count: int, years_active: int) -> list[dict[str, Any]]:
    """Bring the FAQ into the embedded corpus so semantic retrieval can
    surface entries without depending on Thingy picking the explicit
    ``search_faq`` tool. Each FAQ entry becomes one chunk.
    """
    if not faq_path.exists():
        return []
    try:
        data = json.loads(faq_path.read_text(encoding="utf-8"))
    except (ValueError, TypeError):
        return []
    out: list[dict[str, Any]] = []
    replacements = {
        "issueCount": str(issue_count),
        "yearsActive": str(years_active),
    }
    for section in data.get("sections", []) or []:
        if not isinstance(section, dict):
            continue
        title = str(section.get("title") or "").strip()
        if not title:
            continue
        section_slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "section"
        for index, entry in enumerate(section.get("entries", []) or []):
            if not isinstance(entry, dict):
                continue
            q = str(entry.get("question") or "").strip()
            a = str(entry.get("answer") or "").strip()
            if not q or not a:
                continue
            # Resolve known interpolations from the JSON strings.
            a = _NJK_EXPR_RE.sub(lambda m: _resolve_njk_expr(m.group(1), replacements), a)
            text = f"Q. {q}\n\nA. {a}"
            out.append({
                "id": f"faq:{section_slug}:{index}",
                "issue_number": None,
                "subject": f"FAQ — {title}",
                "publish_date": None,
                "issue_year": None,
                "url": "/faq/",
                "section": title,
                "text": text,
                "word_count": len(words(text)),
                "content_kind": "faq",
                "topics": [],
                "source_kind": "faq",
            })
    return out


def _privacy_audit(chunks: list[dict[str, Any]]) -> None:
    """Defensive: refuse to ship a corpus that carries subscriber-count
    text. Catches a regression where a future njk template change might
    embed ``stats.subscriber_count`` into about.njk / support.njk."""
    for chunk in chunks:
        text = str(chunk.get("text") or "")
        lowered = text.lower()
        for needle in CORPUS_PRIVACY_DENYLIST:
            if needle.lower() in lowered:
                raise RuntimeError(
                    f"Privacy denylist hit in chunk {chunk.get('id')!r}: "
                    f"{needle!r} appears in text. Refusing to build corpus."
                )


def chunk_id(issue_number: Any, section: str, index: int, text: str) -> str:
    digest = hashlib.sha256(f"{issue_number}\0{section}\0{index}\0{text}".encode("utf-8")).hexdigest()
    return digest[:16]


def build_corpus(
    archive_dir: Path = ARCHIVE_DIR,
    include_issue_bodies: bool = False,
    site_dir: Path | None = None,
    faq_path: Path | None = None,
) -> dict[str, Any]:
    chunks: list[dict[str, Any]] = []
    issues = []
    links: list[dict[str, Any]] = []
    topic_index: dict[str, dict[str, Any]] = {}
    for path in sorted(archive_dir.glob("*.md"), key=lambda p: issue_sort_key(p.stem)):
        metadata, body = read_issue(path)
        number = metadata.get("number") or path.stem
        subject = metadata.get("subject") or f"Weekly Thing {number}"
        publish_date = metadata.get("publish_date") or ""
        url = f"/archive/{number}/"
        issue_word_count = len(words(body))
        sections = split_sections(body)
        topics = detect_topics(subject, body)
        issue_summary = {
            "abstract": summarize_text(body),
            "key_points": key_points_for_sections(sections),
            "topics": topics,
            "time_sensitivity": time_sensitivity(subject, body),
        }
        issue_sections = [
            {"name": section, "text": section_body, "word_count": len(words(section_body))}
            for section, section_body in sections
        ]
        issue_links = []
        for link in metadata.get("links") or []:
            if not isinstance(link, dict):
                continue
            record = {
                "issue_number": number,
                "subject": subject,
                "publish_date": publish_date,
                "issue_year": parse_year(publish_date),
                "issue_url": url,
                "section": link.get("section"),
                "url": link.get("url"),
                "domain": link.get("domain"),
                "text": link.get("text") or link.get("title") or link.get("heading_context"),
                "heading_context": link.get("heading_context"),
                "context": link.get("context") or link.get("heading_context"),
            }
            if include_issue_bodies:
                issue_links.append(record)
                links.append(record)
        issues.append(
            {
                "number": number,
                "subject": subject,
                "publish_date": publish_date,
                "issue_year": parse_year(publish_date),
                "url": url,
                "word_count": issue_word_count,
                "body_hash": body_hash(body),
                "summary": issue_summary,
                "topics": topics,
            }
        )
        if include_issue_bodies:
            issues[-1]["body"] = body
            issues[-1]["sections"] = issue_sections
            issues[-1]["domains"] = metadata.get("domains") or []
            issues[-1]["links"] = issue_links
        for topic in topics:
            entry = topic_index.setdefault(
                topic,
                {
                    "name": topic,
                    "description": f"Archive material related to {topic.lower()}.",
                    "first_seen": publish_date,
                    "last_seen": publish_date,
                    "issue_numbers": [],
                    "representative_issues": [],
                    "related_topics": [],
                },
            )
            entry["issue_numbers"].append(number)
            if publish_date and (not entry["first_seen"] or publish_date < entry["first_seen"]):
                entry["first_seen"] = publish_date
            if publish_date and publish_date > entry["last_seen"]:
                entry["last_seen"] = publish_date

        for section, section_body in sections:
            for index, chunk_text in enumerate(chunk_section(section_body)):
                if TEMPLATE_LEAK_RE.search(chunk_text):
                    raise RuntimeError(f"Template/generated content leaked into corpus for issue {number}")
                chunks.append(
                    {
                        "id": chunk_id(number, section, index, chunk_text),
                        "issue_number": number,
                        "subject": subject,
                        "publish_date": publish_date,
                        "issue_year": parse_year(publish_date),
                        "url": url,
                        "section": section,
                        "text": chunk_text,
                        "word_count": len(words(chunk_text)),
                        "content_kind": content_kind(section),
                        "topics": topics,
                        "source_kind": "chunk",
                    }
                )

    for entry in topic_index.values():
        entry["representative_issues"] = entry["issue_numbers"][-8:]
        related = set()
        for issue in issues:
            if entry["name"] in issue.get("topics", []):
                related.update(topic for topic in issue.get("topics", []) if topic != entry["name"])
        entry["related_topics"] = sorted(related)[:8]

    # Non-archive sources — origin / membership / FAQ. Embedded alongside
    # issue chunks so semantic retrieval surfaces them naturally without
    # needing dedicated tools. See ``_site_page_chunks`` / ``_faq_chunks``
    # docstrings for the privacy boundary (no subscriber counts).
    years_active = 0
    issue_years = [parse_year(issue.get("publish_date")) for issue in issues if issue.get("publish_date")]
    issue_years = [y for y in issue_years if y]
    if issue_years:
        years_active = max(issue_years) - min(issue_years) + 1
    latest_issue_number = issues[-1]["number"] if issues else None
    if site_dir is not None or SITE_DIR.exists():
        site_chunks = _site_page_chunks(
            site_dir=site_dir or SITE_DIR,
            issue_count=len(issues),
            years_active=years_active,
            latest_issue_number=latest_issue_number,
        )
        chunks.extend(site_chunks)
    if faq_path is not None or FAQ_PATH.exists():
        faq_chunks = _faq_chunks(
            faq_path=faq_path or FAQ_PATH,
            issue_count=len(issues),
            years_active=years_active,
        )
        chunks.extend(faq_chunks)
    _privacy_audit(chunks)

    return {
        "version": 2,
        "source": "apps/site/archive",
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "embedding_model": None,
        "issue_count": len(issues),
        "chunk_count": len(chunks),
        "link_count": len(links),
        "issues": issues,
        "topics": sorted(topic_index.values(), key=lambda item: item["name"]),
        "links": links,
        "chunks": chunks,
    }


# --- blog corpus ---------------------------------------------------------
#
# Jamie's 20-year thingelstad.com blog is a *separate* corpus from the
# Weekly Thing issue archive above. Two corpus objects give hard scope
# isolation: the WT corpus stays byte-identical to today, the blog corpus
# lazy-loads only when a reader's scope asks for it, and "both" is the only
# path that mixes them (a query-time rerank). The builder reuses the same
# chunk primitives (``chunk_section`` / ``content_kind`` / ``words`` /
# ``_privacy_audit``) so the embed + upload tooling is shared verbatim.

# A thingelstad.com (or legacy micro.thingelstad.com) permalink, capturing
# the ``YYYY/MM/DD/slug`` path that uniquely identifies a post. Used both to
# scan issue Journal sections for blog back-references and to normalize a
# blog post's own URL to the same key.
_BLOG_PERMALINK_RE = re.compile(
    r"https?://(?:www\.|micro\.)?thingelstad\.com/(\d{4}/\d{2}/\d{2}/[^\s)\"'<>]+)",
    re.I,
)
# An ``<img …>`` tag's alt text — inlined into the embedding text so photo
# descriptions are searchable (the canonical store keeps the full tag).
_BLOG_IMG_ALT_RE = re.compile(
    r'<img\b[^>]*?\balt\s*=\s*(["\'])(.*?)\1[^>]*?>', re.I | re.S
)
_BLOG_IMG_BARE_RE = re.compile(r"<img\b[^>]*?>", re.I | re.S)


def _normalize_blog_path(path_part: str) -> str:
    """``2026/05/23/slug.html`` → ``2026/05/23/slug`` — the cross-corpus key
    shared by an issue's Journal back-reference and the blog post itself
    (host/scheme/``.html`` dropped)."""
    p = path_part.strip().rstrip("/")
    return re.sub(r"\.html?$", "", p, flags=re.I)


def journal_blog_xref(archive_dir: Path = ARCHIVE_DIR) -> dict[str, list[Any]]:
    """Scan issue archive bodies for thingelstad.com blog back-references
    (the Journal section links to ``thingelstad.com/YYYY/MM/DD/slug`` inline,
    *not* via the curated ``links[]``), returning
    ``{normalized_blog_path: [issue_number, …]}`` so the blog builder can
    stamp ``also_in_issues`` on the matching blog chunks. One-directional
    (blog→issue) for v1: the issue already links to the blog inline."""
    xref: dict[str, set] = {}
    for path in sorted(archive_dir.glob("*.md"), key=lambda p: issue_sort_key(p.stem)):
        metadata, body = read_issue(path)
        number = metadata.get("number") or path.stem
        for match in _BLOG_PERMALINK_RE.finditer(body):
            xref.setdefault(_normalize_blog_path(match.group(1)), set()).add(number)
    return {key: sorted(nums, key=issue_sort_key) for key, nums in xref.items()}


def _blog_embed_text(body: str) -> str:
    """Reduce a native-markdown blog post to embedding-friendly text: inline
    each ``<img>``'s alt text (good photo-search signal), drop any remaining
    HTML tags, normalize whitespace. Markdown links are left intact, matching
    how issue chunks are embedded."""
    s = _BLOG_IMG_ALT_RE.sub(lambda m: f" {m.group(2).strip()} ", body or "")
    s = _BLOG_IMG_BARE_RE.sub(" ", s)
    s = _HTML_TAG_RE.sub(" ", s)
    s = re.sub(r"[ \t]+", " ", s)
    s = re.sub(r"\n\s*\n+", "\n\n", s)
    return s.strip()


def _short_label(text: str, max_words: int = 12) -> str:
    """A readable citation label for an untitled micropost — the first few
    words of its plain text."""
    tokens = plain_text(text).split()
    label = " ".join(tokens[:max_words])
    return label + ("…" if len(tokens) > max_words else "")


def build_blog_corpus(
    blog_dir: Path = BLOG_DIR,
    archive_dir: Path = ARCHIVE_DIR,
    include_xref: bool = True,
) -> dict[str, Any]:
    """Build the blog corpus from ``data/blog/posts/**/*.md``. One chunk per
    ``chunk_section`` piece, ``source_kind: "blog"``, stable id
    ``blog:{microblog_id}:{index}``. Same dict shape as :func:`build_corpus`
    (empty ``issues``/``topics``/``links`` — those power issue-only tools) so
    the embed + upload tooling is reused verbatim. Posts that also appear in a
    Weekly Thing Journal get an ``also_in_issues`` cross-reference."""
    xref = journal_blog_xref(archive_dir) if include_xref else {}
    chunks: list[dict[str, Any]] = []
    post_count = 0
    for path in sorted(blog_dir.rglob("*.md")):
        metadata, body = read_issue(path)
        microblog_id = metadata.get("microblog_id")
        if microblog_id is None:
            raise RuntimeError(f"{path} is missing microblog_id in front matter")
        url = str(metadata.get("url") or "").strip()
        title = str(metadata.get("title") or "").strip()
        post_kind = str(metadata.get("post_kind") or "post").strip()
        section = "Micropost" if post_kind == "micropost" else "Blog post"
        match = _BLOG_PERMALINK_RE.search(url)
        publish_date = None
        if match:
            publish_date = "-".join(match.group(1).split("/")[:3])
        if not publish_date:
            publish_date = str(metadata.get("published") or "")[:10] or None
        also_in_issues = xref.get(_normalize_blog_path(url.split("//", 1)[-1].split("/", 1)[-1])) if url else None
        if not also_in_issues and match:
            also_in_issues = xref.get(_normalize_blog_path(match.group(1)))
        embed_text = _blog_embed_text(body)
        if not embed_text:
            continue
        post_count += 1
        subject = title or _short_label(embed_text)
        for index, chunk_text in enumerate(chunk_section(embed_text)):
            chunk = {
                "id": f"blog:{microblog_id}:{index}",
                "issue_number": None,
                "subject": subject,
                "publish_date": publish_date,
                "issue_year": parse_year(publish_date),
                "url": url,
                "section": section,
                "text": chunk_text,
                "word_count": len(words(chunk_text)),
                "content_kind": "blog",
                "topics": [],
                "source_kind": "blog",
            }
            if also_in_issues:
                chunk["also_in_issues"] = also_in_issues
            chunks.append(chunk)

    _privacy_audit(chunks)

    return {
        "version": 2,
        "source": "data/blog/posts",
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "embedding_model": None,
        "issue_count": 0,
        "post_count": post_count,
        "chunk_count": len(chunks),
        "link_count": 0,
        "issues": [],
        "topics": [],
        "links": [],
        "chunks": chunks,
    }


def _embed_input(chunk: dict[str, Any]) -> str:
    """The text handed to the embedding model for one chunk. Blog chunks get a
    blog-shaped header; everything else keeps the original Weekly-Thing header
    verbatim so existing corpus.json embed inputs stay byte-identical (cache
    stays warm)."""
    if chunk.get("source_kind") == "blog":
        lines = [f"thingelstad.com blog — {chunk.get('publish_date') or ''}".rstrip(" —")]
        if chunk.get("subject"):
            lines.append(f"Post: {chunk['subject']}")
        lines.append(f"Section: {chunk['section']}")
        lines.append(chunk["text"])
        return "\n".join(lines)
    return "\n".join([
        f"Weekly Thing #{chunk['issue_number']}: {chunk['subject']}",
        f"Section: {chunk['section']}",
        f"Topics: {', '.join(chunk.get('topics', []))}",
        chunk["text"],
    ])


def fetch_bedrock_embeddings(inputs: list[str], model: str, input_type: str = "search_document") -> list[list[float]]:
    inputs = [text[:COHERE_EMBED_MAX_TEXT_CHARS] for text in inputs]
    response = boto3.client("bedrock-runtime").invoke_model(
        modelId=model,
        body=json.dumps({"texts": inputs, "input_type": input_type, "truncate": "END"}),
        accept="application/json",
        contentType="application/json",
    )
    data = json.loads(response["body"].read())
    embeddings = data.get("embeddings") or []
    if len(embeddings) != len(inputs):
        raise RuntimeError(f"Bedrock returned {len(embeddings)} embeddings for {len(inputs)} inputs")
    return embeddings


def add_bedrock_embeddings(corpus: dict[str, Any], model: str, dimensions: int, batch_size: int = 96) -> None:
    load_dotenv()
    chunks = corpus["chunks"]
    # Only embed chunks that don't already have an embedding. Callers (the
    # upload script) may have hydrated unchanged chunks from a previous
    # corpus's cache before calling this; those chunks already carry their
    # vector and re-embedding them would just burn money.
    pending = [chunk for chunk in chunks if not chunk.get("embedding")]
    if not pending:
        # All embeddings reused from cache. Set model/dimensions from
        # whatever's already on the chunks.
        corpus["embedding_model"] = model
        if chunks and chunks[0].get("embedding"):
            corpus["embedding_dimensions"] = len(chunks[0]["embedding"])
        else:
            corpus["embedding_dimensions"] = dimensions
        print(f"All {len(chunks)} chunk embeddings reused from cache; skipped Bedrock call.")
        return
    for start in range(0, len(pending), batch_size):
        batch = pending[start : start + batch_size]
        inputs = [_embed_input(chunk) for chunk in batch]
        embeddings = fetch_bedrock_embeddings(inputs, model)
        for chunk, embedding in zip(batch, embeddings):
            chunk["embedding"] = embedding
        print(f"Embedded chunks {start + 1}-{start + len(batch)} of {len(pending)} pending")
    corpus["embedding_model"] = model
    # Derive dimensions from a chunk that has an embedding (works whether
    # this batch added new ones or all were already cached).
    sample = next((c for c in chunks if c.get("embedding")), None)
    corpus["embedding_dimensions"] = len(sample["embedding"]) if sample else dimensions
