"""Unified content pipeline — workshop-as-source.

Two responsibilities:

1. **Build** the static site's archive files (``apps/site/archive/{N}.md`` +
   ``apps/site/_data/emails.json``) from ``data/issues/{N}/`` — the canonical
   per-issue source that workshop_bot commits via its ship sequence. The
   ``build`` subcommand is what ``make build`` and the CI workflow invoke.

2. **Publish** the in-flight workshop issue to Buttondown as a draft.
   ``buttondown_publish_idempotent`` is wrapped by workshop_bot's
   ``send-to-buttondown`` job (and exposed via the ``publish`` CLI for
   manual use). It POSTs on first run, PATCHes on every subsequent run,
   and never sends ``publish_date`` — Jamie schedules and ships from the
   Buttondown UI.

The legacy ``data/buttondown/`` snapshot tree, its three-way push/pull/diff
machinery, and the Liquid-strip transform that turned raw Buttondown bodies
into website-shaped markdown were retired alongside the inversion. The
website's canonical source is now ``data/issues/{N}/archive.md``; the workshop
produces it directly, and the build path here just reads and re-emits with
the 11ty front-matter contract (layout / permalink / tags / audio_* injected
late).

A ``stats`` subcommand refreshes ``apps/site/_data/stats.json`` (subscriber
counts + Stripe balance) — used to be wedged into the pull path, now stands
alone so CI can call it explicitly without entangling with content reads.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests
import yaml
from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).parent))

import fetch_emails

sys.stdout.reconfigure(line_buffering=True)
load_dotenv()

REPO = Path(__file__).resolve().parents[2]
SITE_DIR = REPO / "apps" / "site"
DATA_DIR = SITE_DIR / "_data"
ARCHIVE_DIR = SITE_DIR / "archive"
ISSUES_ROOT = REPO / "data" / "issues"
AUDIO_MANIFEST_PATH = REPO / "data" / "audio" / "manifest.json"
API_BASE = fetch_emails.API_BASE
WEEKLY_THING_ASSETS_BUCKET = os.environ.get(
    "WEEKLY_THING_ASSETS_BUCKET", "files.thingelstad.com"
).strip()

# The notice prepended to every generated archive file. Older files (in
# git history) carry "from data/buttondown" and "from scripts/content";
# parse_archive_file accepts all three so tools that re-read the legacy
# bytes still work, but new writes use the current source.
GENERATED_NOTICE = "<!-- Generated by pipeline/content/content.py from data/issues; do not edit directly. -->"
_LEGACY_NOTICES = (
    "<!-- Generated by pipeline/content/content.py from data/buttondown; do not edit directly. -->",
    "<!-- Generated by scripts/content.py from data/buttondown; do not edit directly. -->",
)


# ---------- shared helpers ----------


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def issue_sort_key(value: Any) -> tuple[int, str]:
    if isinstance(value, int):
        return (value, "")
    match = re.match(r"(\d+)", str(value))
    if not match:
        return (10**9, str(value))
    return (int(match.group(1)), str(value))


def write_json(path: Path, data: Any, ensure_ascii: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=ensure_ascii, indent=2) + "\n", encoding="utf-8")


def load_audio_manifest() -> dict[str, Any]:
    if not AUDIO_MANIFEST_PATH.exists():
        return {}
    return json.loads(AUDIO_MANIFEST_PATH.read_text(encoding="utf-8"))


def audio_fields_for_issue(number: Any, audio_manifest: dict[str, Any]) -> dict[str, Any]:
    record = audio_manifest.get(str(number))
    if not isinstance(record, dict) or not record.get("audio_url"):
        return {}
    fields = {
        "audio_url": record.get("audio_url"),
        "audio_duration_seconds": record.get("audio_duration_seconds"),
        "audio_voice": record.get("audio_voice"),
    }
    byte_size = record.get("audio_byte_size")
    if byte_size is None:
        byte_size = record.get("byte_size")
    if byte_size is not None:
        fields["audio_byte_size"] = byte_size
    return {key: value for key, value in fields.items() if value not in (None, "")}


# ---------- canonical read path: data/issues/{N}/ ----------


def issue_from_canonical(issue_dir: Path) -> dict[str, Any]:
    """Read ``data/issues/{N}/{archive.md, links.json}`` and shape the dict
    write_archive_md and write_emails_json expect."""
    archive_path = issue_dir / "archive.md"
    links_path = issue_dir / "links.json"
    if not archive_path.exists():
        raise RuntimeError(f"{archive_path} is missing")

    content = archive_path.read_text(encoding="utf-8")
    fm_match = re.match(r"^---\n(.+?)\n---\n(.*)$", content, re.DOTALL)
    if not fm_match:
        raise RuntimeError(f"{archive_path} is missing YAML front matter")
    front_matter = yaml.safe_load(fm_match.group(1)) or {}
    body = fm_match.group(2).rstrip("\n")

    links_data = (
        json.loads(links_path.read_text(encoding="utf-8"))
        if links_path.exists()
        else {"notable_links": [], "briefly_links": []}
    )

    return {
        "id": front_matter.get("buttondown_id", ""),
        "number": front_matter["number"],
        "subject": front_matter.get("subject", ""),
        "publish_date": front_matter.get("publish_date", ""),
        "slug": str(front_matter.get("slug", "")),
        "description": front_matter.get("description", "") or "",
        "image": front_matter.get("image") or "",
        "absolute_url": front_matter.get("absolute_url", "") or "",
        "body": body,
        "domains": front_matter.get("domains", []) or [],
        "links": front_matter.get("links", []) or [],
        "notable_links": links_data.get("notable_links", []),
        "briefly_links": links_data.get("briefly_links", []),
        "word_count": front_matter.get("word_count", 0),
    }


def load_issues_canonical() -> list[dict[str, Any]]:
    if not ISSUES_ROOT.exists():
        return []
    issues = []
    for issue_dir in sorted(ISSUES_ROOT.iterdir()):
        if not issue_dir.is_dir():
            continue
        issues.append(issue_from_canonical(issue_dir))
    return sorted(issues, key=lambda item: issue_sort_key(item["number"]))


# ---------- archive + emails.json writers ----------


def write_emails_json(issues: list[dict[str, Any]]) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    audio_manifest = load_audio_manifest()
    entries = []
    for issue in issues:
        entries.append(
            {
                "id": issue["id"],
                "number": issue["number"],
                "subject": issue["subject"],
                "publish_date": issue["publish_date"],
                "slug": issue["slug"],
                "description": issue["description"],
                "image": issue["image"],
                "absolute_url": issue["absolute_url"],
                "domains": issue["domains"],
                "links": issue["links"],
                "notable_links": issue.get("notable_links", []),
                "briefly_links": issue.get("briefly_links", []),
                "word_count": issue.get("word_count", 0),
                **audio_fields_for_issue(issue["number"], audio_manifest),
            }
        )
    write_json(DATA_DIR / "emails.json", entries, ensure_ascii=True)
    print(f"Wrote {len(entries)} entries to {DATA_DIR / 'emails.json'}")


def write_archive_md(issues: list[dict[str, Any]], prune: bool = False) -> None:
    audio_manifest = load_audio_manifest()
    ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
    if prune:
        expected = {f"{issue['number']}.md" for issue in issues}
        for existing in ARCHIVE_DIR.glob("*.md"):
            if existing.name not in expected:
                print(f"  Removing stale archive file: {existing.name}")
                existing.unlink()

    for issue in issues:
        front_matter = {
            "layout": "layouts/issue.njk",
            "buttondown_id": issue["id"],
            "number": issue["number"],
            "subject": issue["subject"],
            "publish_date": issue["publish_date"],
            "slug": issue["slug"],
            "description": issue["description"],
            "image": issue["image"],
            "absolute_url": issue["absolute_url"],
            "domains": issue["domains"],
            "links": issue["links"],
            "word_count": issue.get("word_count", 0),
            "permalink": f"/archive/{issue['number']}/",
            "tags": "issue",
            **audio_fields_for_issue(issue["number"], audio_manifest),
        }
        fm_str = yaml.dump(
            front_matter,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=1000,
        )
        content = f"---\n{fm_str}---\n{GENERATED_NOTICE}\n{issue.get('body', '')}\n"
        (ARCHIVE_DIR / f"{issue['number']}.md").write_text(content, encoding="utf-8")
    print(f"Wrote {len(issues)} archive files to {ARCHIVE_DIR}")


def parse_archive_file(path: Path) -> tuple[dict[str, Any], str]:
    """Parse an apps/site/archive/{N}.md file → (front_matter, body). Tolerates
    all three historical generated-notice prefixes."""
    content = path.read_text(encoding="utf-8")
    for notice in (GENERATED_NOTICE, *_LEGACY_NOTICES):
        content = content.removeprefix(f"{notice}\n")
    match = re.match(r"^---\n(.+?)\n---\n(.*)", content, re.DOTALL)
    if not match:
        raise RuntimeError(f"{path} is missing YAML front matter")
    front_matter = yaml.safe_load(match.group(1)) or {}
    body = match.group(2)
    for notice in (GENERATED_NOTICE, *_LEGACY_NOTICES):
        body = body.removeprefix(f"{notice}\n")
    raw = re.match(r"^\{%\s*raw\s*%\}\n?(.*?)\n?\{%\s*endraw\s*%\}\n?$", body, re.DOTALL)
    return front_matter, raw.group(1) if raw else body.strip()


# ---------- stats refresh (subscriber/premium counts + Stripe balance) ----------


def refresh_stats() -> None:
    existing_stats: dict[str, Any] = {}
    stats_path = DATA_DIR / "stats.json"
    if stats_path.exists():
        existing_stats = json.loads(stats_path.read_text(encoding="utf-8"))

    print("Fetching subscriber stats...")
    try:
        subscriber_count = fetch_emails.fetch_subscriber_count(fetch_emails.get_headers())
        premium_count = fetch_emails.fetch_premium_subscriber_count(fetch_emails.get_headers())
    except Exception as exc:  # noqa: BLE001 — best-effort stats refresh
        print(f"  Warning: Could not fetch subscriber stats: {exc}")
        subscriber_count = existing_stats.get("subscriber_count", 0)
        premium_count = existing_stats.get("premium_subscriber_count", 0)

    print("Fetching Stripe balance...")
    try:
        amount_raised = fetch_emails.fetch_stripe_balance()
    except Exception as exc:  # noqa: BLE001
        print(f"  Warning: Could not fetch Stripe balance: {exc}")
        amount_raised = existing_stats.get("amount_raised", 0)

    write_json(
        stats_path,
        {
            "subscriber_count": subscriber_count,
            "premium_subscriber_count": premium_count,
            "amount_raised": round(amount_raised, 2),
        },
    )


# ---------- build entry point ----------


def build_from_issues_canonical(prune: bool = False) -> list[dict[str, Any]]:
    issues = load_issues_canonical()
    if not issues:
        raise RuntimeError(
            "No canonical issues found under data/issues/. "
            "Workshop_bot's send-to-buttondown ships each issue's archive files there."
        )
    write_emails_json(issues)
    write_archive_md(issues, prune=prune)
    return issues


# ---------- Buttondown ship helper (used by workshop_bot send-to-buttondown) ----------


def headers(content_type: bool = False) -> dict[str, str]:
    api_key = os.environ.get("BUTTONDOWN_API_KEY")
    if not api_key:
        raise RuntimeError("BUTTONDOWN_API_KEY environment variable is required")
    result = {"Authorization": f"Token {api_key}"}
    if content_type:
        result["Content-Type"] = "application/json"
    return result


def _workspace_get_text(issue_number: str, filename: str) -> str | None:
    """Fetch a text asset (utf-8) from the per-issue S3 workspace. Returns
    None if the object doesn't exist; raises on other S3 errors."""
    try:
        import boto3
        from botocore.exceptions import ClientError
    except ImportError as exc:
        raise RuntimeError("boto3 is required to read the S3 workspace") from exc
    key = f"weekly-thing/{issue_number}/{filename}"
    try:
        resp = boto3.client("s3").get_object(
            Bucket=WEEKLY_THING_ASSETS_BUCKET, Key=key,
        )
    except ClientError as exc:
        code = exc.response.get("Error", {}).get("Code", "")
        if code in ("NoSuchKey", "404"):
            return None
        raise
    return resp["Body"].read().decode("utf-8")


def _workspace_put_text(issue_number: str, filename: str, content: str) -> None:
    """Write a text asset back to the per-issue S3 workspace. Used by
    buttondown_publish_idempotent to persist the freshly-minted buttondown_id
    (and absolute_url) back to metadata.json."""
    try:
        import boto3
    except ImportError as exc:
        raise RuntimeError("boto3 is required to write the S3 workspace") from exc
    key = f"weekly-thing/{issue_number}/{filename}"
    ctype = {
        "metadata.json": "application/json; charset=utf-8",
        "buttondown.md": "text/markdown; charset=utf-8",
    }.get(filename, "text/plain; charset=utf-8")
    boto3.client("s3").put_object(
        Bucket=WEEKLY_THING_ASSETS_BUCKET,
        Key=key,
        Body=content.encode("utf-8"),
        ContentType=ctype,
    )


class ButtondownPublishError(RuntimeError):
    """Raised when buttondown_publish_idempotent can't complete (missing
    buttondown.md/metadata.json, missing response id, or any unhandled
    4xx/5xx). The workshop_bot job surfaces the message directly in #editorial."""


def buttondown_publish_idempotent(
    issue_number: str | int, *, dry_run: bool = False,
) -> dict[str, Any]:
    """Create or update a Buttondown draft for ``issue_number``.

    Reads ``buttondown.md`` + ``metadata.json`` from the issue's S3 workspace.
    If ``metadata.json`` already carries a ``buttondown_id``, PATCHes that
    draft. Otherwise POSTs a new draft, then writes the freshly-minted id
    (and absolute_url) back to ``metadata.json``.

    **``publish_date`` is never sent.** The publisher pushes
    subject / body / slug / description / image / status=draft — Jamie
    schedules and sends from the Buttondown UI.

    On a 404 from PATCH (the draft was deleted in Buttondown UI between
    runs), falls through to POST and updates ``buttondown_id``.

    Returns::

        {
            "action": "created" | "updated" | "would_create" | "would_update",
            "id": "<buttondown-uuid>",
            "absolute_url": "https://buttondown.com/.../...",
            "subject": "...",
            "slug": "...",
            "body_chars": int,
            "description_chars": int,
        }
    """
    number = str(issue_number)
    body = _workspace_get_text(number, "buttondown.md")
    if body is None:
        raise ButtondownPublishError(
            f"No buttondown.md at s3://{WEEKLY_THING_ASSETS_BUCKET}/weekly-thing/{number}/buttondown.md — "
            "the issue isn't ready. Run `/eddy issue publish` first."
        )
    meta_raw = _workspace_get_text(number, "metadata.json")
    if meta_raw is None:
        raise ButtondownPublishError(
            f"No metadata.json for #{number} — run `/eddy issue subject` first."
        )
    meta = json.loads(meta_raw)
    subject = meta.get("subject") or f"WT{number}"
    description = meta.get("description") or ""
    image = meta.get("image") or ""
    slug = str(meta.get("slug") or number)
    existing_id = meta.get("buttondown_id")

    payload: dict[str, Any] = {
        "subject": subject,
        "body": body,
        "status": "draft",
        "email_type": "public",
        "slug": slug,
        "description": description,
    }
    if image:
        payload["image"] = image

    base_result: dict[str, Any] = {
        "subject": subject,
        "slug": slug,
        "body_chars": len(body),
        "description_chars": len(description),
    }

    if dry_run:
        return {
            **base_result,
            "action": "would_update" if existing_id else "would_create",
            "id": existing_id or "(none)",
            "absolute_url": meta.get("absolute_url", ""),
        }

    # 1) If we have a known id, try PATCH first.
    if existing_id:
        url = f"{API_BASE}/emails/{existing_id}"
        resp = requests.patch(url, headers=headers(content_type=True), json=payload)
        if resp.status_code == 404:
            # The draft was deleted in Buttondown's UI; fall through to POST.
            existing_id = None
        elif resp.status_code >= 400:
            raise ButtondownPublishError(
                f"Buttondown PATCH /emails/{existing_id} failed "
                f"({resp.status_code}): {resp.text[:500]}"
            )
        else:
            data = resp.json() if resp.text else {}
            resolved_id = data.get("id") or existing_id
            resolved_url = data.get("absolute_url") or meta.get("absolute_url") or ""
            if resolved_url and resolved_url != meta.get("absolute_url"):
                meta["absolute_url"] = resolved_url
                _workspace_put_text(number, "metadata.json", json.dumps(meta, indent=2) + "\n")
            return {
                **base_result, "action": "updated",
                "id": resolved_id, "absolute_url": resolved_url,
            }

    # 2) POST to create a new draft.
    resp = requests.post(f"{API_BASE}/emails", headers=headers(content_type=True), json=payload)
    if resp.status_code >= 400:
        raise ButtondownPublishError(
            f"Buttondown POST /emails failed ({resp.status_code}): {resp.text[:500]}"
        )
    data = resp.json()
    new_id = data.get("id")
    if not new_id:
        raise ButtondownPublishError("Buttondown POST succeeded but the response had no `id`.")

    new_url = data.get("absolute_url") or ""

    meta["buttondown_id"] = new_id
    if new_url:
        meta["absolute_url"] = new_url
    _workspace_put_text(number, "metadata.json", json.dumps(meta, indent=2) + "\n")

    return {**base_result, "action": "created", "id": new_id, "absolute_url": new_url}


def publish_to_buttondown(args: argparse.Namespace) -> None:
    """CLI shim around :func:`buttondown_publish_idempotent`."""
    number = str(args.issue)
    try:
        result = buttondown_publish_idempotent(
            number, dry_run=getattr(args, "dry_run", False),
        )
    except ButtondownPublishError as exc:
        raise SystemExit(str(exc))
    action = result["action"]
    if action.startswith("would_"):
        verb = "create" if action == "would_create" else "update"
        print(
            f"[dry-run] would {verb} Buttondown draft for #{number}: "
            f"subject={result['subject']!r}, slug={result['slug']!r}, "
            f"id={result['id']}, body={result['body_chars']} chars, "
            f"description={result['description_chars']} chars"
        )
        return
    verb = "Created" if action == "created" else "Updated"
    print(f"{verb} Buttondown draft for #{number}: id={result['id']} subject={result['subject']!r}")
    print("Review it in the Buttondown UI, then schedule the send.")


# ---------- CLI ----------


def cmd_build(args: argparse.Namespace) -> None:
    build_from_issues_canonical(prune=args.prune)


def cmd_stats(_args: argparse.Namespace) -> None:
    refresh_stats()


def main() -> None:
    parser = argparse.ArgumentParser(description="The Weekly Thing content pipeline")
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="Build archive files from data/issues/")
    build_parser.add_argument("--prune", action="store_true", help="Remove archive files not in data/issues/")

    subparsers.add_parser("stats", help="Refresh apps/site/_data/stats.json (subscriber/premium counts + Stripe balance)")

    publish_parser = subparsers.add_parser(
        "publish",
        help="Create or update a Buttondown draft from the issue's buttondown.md + metadata.json in S3",
    )
    publish_parser.add_argument("--issue", required=True, help="Issue number to publish")
    publish_parser.add_argument("--dry-run", action="store_true", help="Preview without touching Buttondown")

    args = parser.parse_args()
    if args.command == "build":
        cmd_build(args)
    elif args.command == "stats":
        cmd_stats(args)
    elif args.command == "publish":
        publish_to_buttondown(args)


if __name__ == "__main__":
    main()
