"""Unified Buttondown content pipeline.

This script keeps a durable, tracked Buttondown baseline in data/buttondown,
builds the Eleventy archive from that baseline, and safely syncs local raw
body/metadata edits back to Buttondown with three-way conflict detection.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests
import yaml
from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).parent))

import fetch_emails
import process_emails

sys.stdout.reconfigure(line_buffering=True)
load_dotenv()

REPO = Path(__file__).resolve().parents[2]
SITE_DIR = REPO / "apps" / "site"
DATA_DIR = SITE_DIR / "_data"
ARCHIVE_DIR = SITE_DIR / "archive"
SNAPSHOT_ROOT = REPO / "data" / "buttondown"
SNAPSHOT_DIR = SNAPSHOT_ROOT / "emails"
BODY_DIR = SNAPSHOT_ROOT / "bodies"
MANIFEST_PATH = SNAPSHOT_ROOT / "manifest.json"
AUDIO_MANIFEST_PATH = REPO / "data" / "audio" / "manifest.json"
API_BASE = fetch_emails.API_BASE

SNAPSHOT_METADATA_FIELDS = [
    "id",
    "number",
    "subject",
    "description",
    "image",
    "slug",
    "publish_date",
    "absolute_url",
    "email_type",
    "status",
    "secondary_id",
]

HASH_FIELDS = [*SNAPSHOT_METADATA_FIELDS, "body"]
PUSH_FIELDS = ["body", "subject", "description", "image", "slug"]
GENERATED_NOTICE = "<!-- Generated by pipeline/content/content.py from data/buttondown; do not edit directly. -->"
LEGACY_GENERATED_NOTICE = "<!-- Generated by scripts/content.py from data/buttondown; do not edit directly. -->"


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def issue_sort_key(value: Any) -> tuple[int, str]:
    if isinstance(value, int):
        return (value, "")
    match = re.match(r"(\d+)", str(value))
    if not match:
        return (10**9, str(value))
    return (int(match.group(1)), str(value))


def snapshot_path(number: Any) -> Path:
    return SNAPSHOT_DIR / f"{number}.json"


def body_path(number: Any) -> Path:
    return BODY_DIR / f"{number}.md"


def canonical_hash(data: dict[str, Any]) -> str:
    payload = {field: data.get(field) for field in HASH_FIELDS}
    encoded = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def write_json(path: Path, data: Any, ensure_ascii: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=ensure_ascii, indent=2) + "\n", encoding="utf-8")


def load_audio_manifest() -> dict[str, Any]:
    if not AUDIO_MANIFEST_PATH.exists():
        return {}
    return json.loads(AUDIO_MANIFEST_PATH.read_text(encoding="utf-8"))


def audio_fields_for_issue(number: Any, audio_manifest: dict[str, Any]) -> dict[str, Any]:
    record = audio_manifest.get(str(number))
    if not isinstance(record, dict) or not record.get("audio_url"):
        return {}
    fields = {
        "audio_url": record.get("audio_url"),
        "audio_duration_seconds": record.get("audio_duration_seconds"),
        "audio_voice": record.get("audio_voice"),
    }
    byte_size = record.get("audio_byte_size")
    if byte_size is None:
        byte_size = record.get("byte_size")
    if byte_size is not None:
        fields["audio_byte_size"] = byte_size
    return {key: value for key, value in fields.items() if value not in (None, "")}


def make_snapshot(issue: dict[str, Any], fetched_at: str | None = None) -> dict[str, Any]:
    snapshot = {field: issue.get(field, "") for field in SNAPSHOT_METADATA_FIELDS}
    snapshot["body"] = issue.get("body", "")
    snapshot["image"] = snapshot.get("image") or ""
    snapshot["description"] = snapshot.get("description") or ""
    snapshot["absolute_url"] = snapshot.get("absolute_url") or ""
    snapshot["email_type"] = snapshot.get("email_type") or "public"
    snapshot["status"] = snapshot.get("status") or ""
    snapshot["fetched_at"] = fetched_at or now_iso()
    snapshot["source_hash"] = canonical_hash(snapshot)
    return snapshot


def write_snapshot(snapshot: dict[str, Any]) -> None:
    number = snapshot["number"]
    body_path(number).parent.mkdir(parents=True, exist_ok=True)
    body_path(number).write_text(snapshot.get("body", ""), encoding="utf-8")
    metadata = {field: snapshot.get(field, "") for field in SNAPSHOT_METADATA_FIELDS}
    metadata["body_path"] = f"data/buttondown/bodies/{number}.md"
    metadata["fetched_at"] = snapshot.get("fetched_at") or now_iso()
    metadata["source_hash"] = canonical_hash(snapshot)
    write_json(snapshot_path(number), metadata)


def load_snapshot_file(path: Path) -> dict[str, Any]:
    snapshot = json.loads(path.read_text(encoding="utf-8"))
    raw_body = snapshot.get("body")
    if raw_body is None:
        path_value = snapshot.get("body_path") or f"data/buttondown/bodies/{snapshot['number']}.md"
        raw_path = REPO / path_value
        if not raw_path.exists():
            raise RuntimeError(f"{path} references missing raw body file: {path_value}")
        raw_body = raw_path.read_text(encoding="utf-8")
    snapshot["body"] = raw_body
    return snapshot


def load_snapshots() -> list[dict[str, Any]]:
    if not SNAPSHOT_DIR.exists():
        return []
    snapshots = []
    for path in sorted(SNAPSHOT_DIR.glob("*.json")):
        snapshots.append(load_snapshot_file(path))
    return sorted(snapshots, key=lambda item: issue_sort_key(item["number"]))


def write_manifest(snapshots: list[dict[str, Any]]) -> None:
    entries = []
    for item in sorted(snapshots, key=lambda s: issue_sort_key(s["number"])):
        entries.append(
            {
                "number": item["number"],
                "id": item["id"],
                "subject": item.get("subject", ""),
                "publish_date": item.get("publish_date", ""),
                "source_hash": item.get("source_hash", ""),
                "fetched_at": item.get("fetched_at", ""),
                "snapshot_path": f"data/buttondown/emails/{item['number']}.json",
                "body_path": f"data/buttondown/bodies/{item['number']}.md",
                "archive_path": f"apps/site/archive/{item['number']}.md",
            }
        )
    write_json(
        MANIFEST_PATH,
        {
            "generated_at": now_iso(),
            "count": len(entries),
            "emails": entries,
        },
    )


def headers(content_type: bool = False) -> dict[str, str]:
    api_key = os.environ.get("BUTTONDOWN_API_KEY")
    if not api_key:
        raise RuntimeError("BUTTONDOWN_API_KEY environment variable is required")
    result = {"Authorization": f"Token {api_key}"}
    if content_type:
        result["Content-Type"] = "application/json"
    return result


def fetch_all_emails() -> list[dict[str, Any]]:
    emails = []
    url = f"{API_BASE}/emails"
    params = {
        "status": "sent",
        "email_type": "public",
        "ordering": "publish_date",
        "page_size": 100,
    }
    while url:
        print(f"  Fetching {url} ...")
        response = requests.get(url, headers=headers(), params=params)
        response.raise_for_status()
        data = response.json()
        emails.extend(data.get("results", []))
        url = data.get("next")
        params = {}
    return emails


def fetch_latest_email() -> dict[str, Any] | None:
    response = requests.get(
        f"{API_BASE}/emails",
        headers=headers(),
        params={
            "status": "sent",
            "email_type": "public",
            "ordering": "-publish_date",
            "page_size": 1,
        },
    )
    response.raise_for_status()
    results = response.json().get("results", [])
    return results[0] if results else None


def fetch_email_by_id(email_id: str) -> dict[str, Any]:
    response = requests.get(f"{API_BASE}/emails/{email_id}", headers=headers())
    response.raise_for_status()
    return response.json()


def strip_editor_mode_comment(body: str) -> str:
    return re.sub(r"<!--\s*buttondown-editor-mode:[^>]*-->\s*", "", body, flags=re.I)


def tokenize_template(body: str) -> list[tuple[str, str]]:
    token_re = re.compile(r"({%[\s\S]*?%}|{{[\s\S]*?}})")
    tokens = []
    pos = 0
    for match in token_re.finditer(body):
        if match.start() > pos:
            tokens.append(("text", body[pos:match.start()]))
        token = match.group(0)
        if token.startswith("{%"):
            tokens.append(("tag", token[2:-2].strip()))
        else:
            tokens.append(("var", token[2:-2].strip()))
        pos = match.end()
    if pos < len(body):
        tokens.append(("text", body[pos:]))
    return tokens


def eval_archive_condition(expr: str) -> bool | None:
    expr = " ".join(expr.strip().split())
    if expr == "medium == 'email'" or expr == 'medium == "email"':
        return False
    if expr == "medium == 'web'" or expr == 'medium == "web"':
        return True
    if expr.startswith("subscriber."):
        return False
    return None


def render_archive_variable(expr: str, issue: dict[str, Any]) -> str:
    expr = " ".join(expr.strip().split())
    if expr == "email.subject":
        return issue.get("subject", "")
    if expr in {"email_url", "email.url", "email_link"}:
        return issue.get("absolute_url", "") or f"/archive/{issue['number']}/"
    if expr == "subscribe_url":
        return "https://weekly.thingelstad.com/"
    if expr in {"subscribe_form", "unsubscribe_url", "manage_subscription_url", "upgrade_url", "premium_subscribe_url"}:
        return ""
    if expr.startswith("subscriber.") or expr.startswith("survey."):
        return ""
    return ""


def render_template_tokens(tokens: list[tuple[str, str]], issue: dict[str, Any], start: int = 0, stop_tags: set[str] | None = None) -> tuple[str, int, str | None]:
    output = []
    i = start
    stop_tags = stop_tags or set()
    while i < len(tokens):
        kind, value = tokens[i]
        if kind == "text":
            output.append(value)
            i += 1
            continue
        if kind == "var":
            output.append(render_archive_variable(value, issue))
            i += 1
            continue
        tag_name = value.split()[0] if value else ""
        if tag_name in stop_tags:
            return "".join(output), i, tag_name
        if tag_name == "if":
            rendered, i = render_if_block(tokens, issue, i)
            output.append(rendered)
            continue
        if tag_name == "for":
            i = skip_block(tokens, i, "for", "endfor")
            continue
        # Unknown top-level Django tag: drop the tag but keep surrounding text.
        i += 1
    return "".join(output), i, None


def skip_block(tokens: list[tuple[str, str]], start: int, open_name: str, close_name: str) -> int:
    depth = 0
    i = start
    while i < len(tokens):
        kind, value = tokens[i]
        tag_name = value.split()[0] if kind == "tag" and value else ""
        if tag_name == open_name:
            depth += 1
        elif tag_name == close_name:
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return i


def render_if_block(tokens: list[tuple[str, str]], issue: dict[str, Any], start: int) -> tuple[str, int]:
    _, opening = tokens[start]
    branches = [(opening[2:].strip(), start + 1)]
    i = start + 1
    depth = 0
    while i < len(tokens):
        kind, value = tokens[i]
        tag_name = value.split()[0] if kind == "tag" and value else ""
        if tag_name == "if":
            depth += 1
        elif tag_name == "endif":
            if depth == 0:
                end = i
                break
            depth -= 1
        elif depth == 0 and tag_name in {"elif", "else"}:
            branches[-1] = (branches[-1][0], branches[-1][1], i)
            branches.append((value[4:].strip() if tag_name == "elif" else "else", i + 1))
        i += 1
    else:
        # Unbalanced block: safest archive rendering is to drop the opener and
        # render following text normally.
        return "", start + 1

    branches[-1] = (branches[-1][0], branches[-1][1], end)
    if branches[0][0].startswith("subscriber."):
        return "", end + 1
    for condition, body_start, body_end in branches:
        if condition == "else":
            rendered, _, _ = render_template_tokens(tokens[body_start:body_end], issue)
            return rendered, end + 1
        value = eval_archive_condition(condition)
        if value is True:
            rendered, _, _ = render_template_tokens(tokens[body_start:body_end], issue)
            return rendered, end + 1
        if value is None:
            # Unknown personalized condition: do not render it publicly.
            continue
    return "", end + 1


def archive_body_from_issue(issue: dict[str, Any]) -> str:
    body = strip_editor_mode_comment(issue.get("body", ""))
    rendered, _, _ = render_template_tokens(tokenize_template(body), issue)
    rendered = re.sub(r"\*\|[A-Z_:]+\|\*", "", rendered)
    rendered = re.sub(r"\n{3,}", "\n\n", rendered)
    rendered = "\n".join(line.rstrip() for line in rendered.splitlines())
    return rendered.strip()


def issue_from_snapshot(snapshot: dict[str, Any]) -> dict[str, Any]:
    body = archive_body_from_issue(snapshot)
    link_data = process_emails.extract_links(body)
    links = link_data["all_curated"]
    return {
        "id": snapshot.get("id", ""),
        "number": snapshot["number"],
        "subject": snapshot.get("subject", ""),
        "publish_date": snapshot.get("publish_date", ""),
        "slug": snapshot.get("slug", ""),
        "description": snapshot.get("description", ""),
        "image": snapshot.get("image") or "",
        "absolute_url": snapshot.get("absolute_url", ""),
        "body": body,
        "domains": process_emails.extract_domains(links),
        "links": links,
        "notable_links": link_data["notable"],
        "briefly_links": link_data["briefly"],
        "word_count": process_emails.count_words(body),
    }


def write_emails_json(issues: list[dict[str, Any]]) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    audio_manifest = load_audio_manifest()
    entries = []
    for issue in issues:
        entries.append(
            {
                "id": issue["id"],
                "number": issue["number"],
                "subject": issue["subject"],
                "publish_date": issue["publish_date"],
                "slug": issue["slug"],
                "description": issue["description"],
                "image": issue["image"],
                "absolute_url": issue["absolute_url"],
                "domains": issue["domains"],
                "links": issue["links"],
                "notable_links": issue.get("notable_links", []),
                "briefly_links": issue.get("briefly_links", []),
                "word_count": issue.get("word_count", 0),
                **audio_fields_for_issue(issue["number"], audio_manifest),
            }
        )
    write_json(DATA_DIR / "emails.json", entries, ensure_ascii=True)
    print(f"Wrote {len(entries)} entries to {DATA_DIR / 'emails.json'}")


def write_archive_md(issues: list[dict[str, Any]], prune: bool = False) -> None:
    audio_manifest = load_audio_manifest()
    ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
    if prune:
        expected = {f"{issue['number']}.md" for issue in issues}
        for existing in ARCHIVE_DIR.glob("*.md"):
            if existing.name not in expected:
                print(f"  Removing stale archive file: {existing.name}")
                existing.unlink()

    for issue in issues:
        front_matter = {
            "layout": "layouts/issue.njk",
            "buttondown_id": issue["id"],
            "number": issue["number"],
            "subject": issue["subject"],
            "publish_date": issue["publish_date"],
            "slug": issue["slug"],
            "description": issue["description"],
            "image": issue["image"],
            "absolute_url": issue["absolute_url"],
            "domains": issue["domains"],
            "links": issue["links"],
            "word_count": issue.get("word_count", 0),
            "permalink": f"/archive/{issue['number']}/",
            "tags": "issue",
            **audio_fields_for_issue(issue["number"], audio_manifest),
        }
        fm_str = yaml.dump(
            front_matter,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=1000,
        )
        content = f"---\n{fm_str}---\n{GENERATED_NOTICE}\n{issue.get('body', '')}\n"
        (ARCHIVE_DIR / f"{issue['number']}.md").write_text(content, encoding="utf-8")
    print(f"Wrote {len(issues)} archive files to {ARCHIVE_DIR}")


def refresh_stats() -> None:
    existing_stats = {}
    stats_path = DATA_DIR / "stats.json"
    if stats_path.exists():
        existing_stats = json.loads(stats_path.read_text(encoding="utf-8"))

    print("Fetching subscriber stats...")
    try:
        subscriber_count = fetch_emails.fetch_subscriber_count(fetch_emails.get_headers())
        premium_count = fetch_emails.fetch_premium_subscriber_count(fetch_emails.get_headers())
    except Exception as exc:
        print(f"  Warning: Could not fetch subscriber stats: {exc}")
        subscriber_count = existing_stats.get("subscriber_count", 0)
        premium_count = existing_stats.get("premium_subscriber_count", 0)

    print("Fetching Stripe balance...")
    try:
        amount_raised = fetch_emails.fetch_stripe_balance()
    except Exception as exc:
        print(f"  Warning: Could not fetch Stripe balance: {exc}")
        amount_raised = existing_stats.get("amount_raised", 0)

    write_json(
        stats_path,
        {
            "subscriber_count": subscriber_count,
            "premium_subscriber_count": premium_count,
            "amount_raised": round(amount_raised, 2),
        },
    )


def build_from_snapshots(prune: bool = False) -> list[dict[str, Any]]:
    snapshots = load_snapshots()
    if not snapshots:
        raise RuntimeError("No Buttondown snapshots found. Run content pull --all first.")
    issues = [issue_from_snapshot(snapshot) for snapshot in snapshots]
    write_emails_json(issues)
    write_archive_md(issues, prune=prune)
    return issues


def pull_all(args: argparse.Namespace) -> None:
    raw_emails = fetch_all_emails()
    issues = process_emails.process(raw_emails)
    fetched_at = now_iso()
    print(f"Writing {len(issues)} Buttondown snapshots...")
    current_files = {f"{issue['number']}.json" for issue in issues}
    current_bodies = {f"{issue['number']}.md" for issue in issues}
    if SNAPSHOT_DIR.exists():
        for existing in SNAPSHOT_DIR.glob("*.json"):
            if existing.name not in current_files:
                print(f"  Removing stale snapshot: {existing.name}")
                existing.unlink()
    if BODY_DIR.exists():
        for existing in BODY_DIR.glob("*.md"):
            if existing.name not in current_bodies:
                print(f"  Removing stale raw body: {existing.name}")
                existing.unlink()
    for issue in issues:
        source = next(email for email in raw_emails if email.get("id") == issue["id"])
        snapshot = make_snapshot({**source, "number": issue["number"]}, fetched_at=fetched_at)
        write_snapshot(snapshot)
    write_manifest(load_snapshots())
    refresh_stats()
    if not args.no_build:
        build_from_snapshots(prune=args.prune)
    print(f"Done. Pulled {len(issues)} issue snapshots.")


def derive_issue_number(email: dict[str, Any]) -> int | str:
    slug = str(email.get("slug") or "").strip()
    if re.fullmatch(r"\d+", slug):
        return int(slug)
    if re.fullmatch(r"\d+-special", slug):
        return slug

    subject = email.get("subject", "")
    subject_number = process_emails.extract_subject_number(subject)
    if subject_number is not None:
        if process_emails.is_special_issue(subject) and snapshot_path(subject_number).exists():
            return f"{subject_number}-special"
        return subject_number

    raise RuntimeError(
        "Could not derive archive issue number from latest Buttondown email. "
        f"Expected numeric slug or parseable subject; got slug={slug!r}, subject={subject!r}."
    )


def pull_latest(args: argparse.Namespace) -> None:
    email = fetch_latest_email()
    if not email:
        print("No emails found.")
        return
    number = derive_issue_number(email)
    snapshot = make_snapshot({**email, "number": number})
    existing = snapshot_path(number)
    if existing.exists() and args.skip_existing:
        current = load_snapshot_file(existing)
        if current.get("source_hash") == snapshot["source_hash"]:
            print(f"Issue #{number} already matches Buttondown at {existing}; nothing to do.")
            return
        print(f"Issue #{number} already exists, but Buttondown has changed; updating snapshot.")
    write_snapshot(snapshot)
    write_manifest(load_snapshots())
    refresh_stats()
    if not args.no_build:
        build_from_snapshots(prune=False)
    print(f"Done. Latest issue is #{number} — {snapshot['subject']}")


def parse_archive_file(path: Path) -> tuple[dict[str, Any], str]:
    content = path.read_text(encoding="utf-8")
    content = content.removeprefix(f"{GENERATED_NOTICE}\n")
    content = content.removeprefix(f"{LEGACY_GENERATED_NOTICE}\n")
    match = re.match(r"^---\n(.+?)\n---\n(.*)", content, re.DOTALL)
    if not match:
        raise RuntimeError(f"{path} is missing YAML front matter")
    front_matter = yaml.safe_load(match.group(1)) or {}
    body = match.group(2)
    body = body.removeprefix(f"{GENERATED_NOTICE}\n")
    body = body.removeprefix(f"{LEGACY_GENERATED_NOTICE}\n")
    raw = re.match(r"^\{%\s*raw\s*%\}\n?(.*?)\n?\{%\s*endraw\s*%\}\n?$", body, re.DOTALL)
    return front_matter, raw.group(1) if raw else body.strip()


def local_values(front_matter: dict[str, Any], body: str) -> dict[str, Any]:
    return {
        "body": body,
        "subject": front_matter.get("subject", ""),
        "description": front_matter.get("description", ""),
        "image": front_matter.get("image") or "",
        "slug": str(front_matter.get("slug", "")),
    }


def normalize(value: Any) -> str:
    return "" if value is None else str(value)


def changed_fields(snapshot: dict[str, Any], local: dict[str, Any], fields: list[str] | None = None) -> dict[str, Any]:
    changes = {}
    for field in fields or PUSH_FIELDS:
        if normalize(local.get(field)) != normalize(snapshot.get(field)):
            changes[field] = local.get(field) or ""
    return changes


def iter_issue_snapshots(issue: str | None = None) -> list[dict[str, Any]]:
    snapshots = load_snapshots()
    if issue:
        snapshots = [snapshot for snapshot in snapshots if str(snapshot["number"]) == str(issue)]
    return snapshots


def load_committed_snapshot(number: Any) -> dict[str, Any] | None:
    metadata_path = f"data/buttondown/emails/{number}.json"
    body_path = f"data/buttondown/bodies/{number}.md"
    try:
        metadata_result = subprocess.run(
            ["git", "show", f"HEAD:{metadata_path}"],
            cwd=REPO,
            check=True,
            text=True,
            capture_output=True,
        )
        body_result = subprocess.run(
            ["git", "show", f"HEAD:{body_path}"],
            cwd=REPO,
            check=True,
            text=True,
            capture_output=True,
        )
    except subprocess.CalledProcessError:
        return None
    snapshot = json.loads(metadata_result.stdout)
    snapshot["body"] = body_result.stdout
    return snapshot


def find_raw_snapshot_changes(issue: str | None = None) -> list[dict[str, Any]]:
    changes = []
    for snapshot in iter_issue_snapshots(issue):
        baseline = load_committed_snapshot(snapshot["number"])
        if not baseline:
            print(f"Warning: no committed snapshot baseline for #{snapshot['number']}; skipping.")
            continue
        fields = changed_fields(baseline, snapshot)
        if fields:
            changes.append({"baseline": baseline, "snapshot": snapshot, "fields": fields})
    return changes


def print_changes(changes: list[dict[str, Any]]) -> None:
    if not changes:
        print("No local changes detected.")
        return
    print(f"Found {len(changes)} changed issue(s):")
    for change in changes:
        snapshot = change["snapshot"]
        names = ", ".join(change["fields"].keys())
        print(f"  #{snapshot['number']} {snapshot.get('subject', '')}")
        print(f"    Changed fields: {names}")


def patch_with_retry(url: str, fields: dict[str, Any], max_attempts: int = 5) -> requests.Response | None:
    for attempt in range(max_attempts):
        response = requests.patch(url, headers=headers(content_type=True), json=fields)
        if response.status_code != 429:
            return response
        retry_after = response.headers.get("Retry-After", "5")
        try:
            wait = max(1, int(retry_after))
        except ValueError:
            wait = 5
        print(f"    429 rate-limited; sleeping {wait}s (attempt {attempt + 1}/{max_attempts})")
        time.sleep(wait)
    return None


def classify_push_fields(
    snapshot: dict[str, Any],
    local_fields: dict[str, Any],
    live: dict[str, Any],
    force: bool = False,
) -> tuple[dict[str, Any], list[str]]:
    safe_fields = {}
    conflicts = []
    for field, local_value in local_fields.items():
        baseline_value = normalize(snapshot.get(field))
        remote_value = normalize(live.get(field))
        if remote_value != baseline_value and remote_value != normalize(local_value):
            conflicts.append(field)
        else:
            safe_fields[field] = local_value
    if conflicts and force:
        safe_fields.update({field: local_fields[field] for field in conflicts})
    return safe_fields, conflicts


def push(args: argparse.Namespace) -> None:
    changes = find_raw_snapshot_changes(args.issue)
    print_changes(changes)
    if not changes:
        return
    if args.dry_run or not args.yes:
        print("\nDry run only. Re-run with --yes to update Buttondown.")
        return

    refreshed = {snapshot["number"]: snapshot for snapshot in load_snapshots()}
    for change in changes:
        baseline = change["baseline"]
        snapshot = change["snapshot"]
        fields = change["fields"]
        print(f"\n  #{snapshot['number']} ({snapshot.get('subject', '')})")
        live = fetch_email_by_id(snapshot["id"])
        safe_fields, conflicts = classify_push_fields(baseline, fields, live, args.force)

        if conflicts and not args.force:
            print(f"    CONFLICT: remote also changed {', '.join(conflicts)}; skipping.")
            continue

        if "body" in safe_fields and not str(safe_fields["body"]).strip():
            print("    ERROR: refusing to push empty body; skipping.")
            continue
        if not safe_fields:
            print("    No safe fields to push.")
            refreshed[snapshot["number"]] = make_snapshot({**live, "number": snapshot["number"]})
            continue

        response = patch_with_retry(f"{API_BASE}/emails/{snapshot['id']}", safe_fields)
        if response is None:
            print("    ERROR: giving up after repeated rate-limit retries.")
            continue
        if not response.ok:
            print(f"    ERROR: {response.status_code} — {response.text[:200]}")
            continue

        updated = response.json()
        new_snapshot = make_snapshot({**updated, "number": snapshot["number"]})
        write_snapshot(new_snapshot)
        refreshed[snapshot["number"]] = new_snapshot
        print(f"    Updated successfully ({', '.join(safe_fields.keys())})")

    write_manifest(list(refreshed.values()))


def cmd_build(args: argparse.Namespace) -> None:
    build_from_snapshots(prune=args.prune)


def cmd_diff(args: argparse.Namespace) -> None:
    print_changes(find_raw_snapshot_changes(args.issue))


def main() -> None:
    parser = argparse.ArgumentParser(description="The Weekly Thing content pipeline")
    subparsers = parser.add_subparsers(dest="command", required=True)

    pull_parser = subparsers.add_parser("pull", help="Pull Buttondown snapshots")
    pull_group = pull_parser.add_mutually_exclusive_group(required=True)
    pull_group.add_argument("--all", action="store_true", help="Fetch all sent public issues")
    pull_group.add_argument("--latest", action="store_true", help="Fetch the latest sent public issue")
    pull_parser.add_argument("--skip-existing", action="store_true", help="No-op if latest snapshot exists")
    pull_parser.add_argument("--no-build", action="store_true", help="Only write snapshots")
    pull_parser.add_argument("--prune", action="store_true", help="Remove archive files not in snapshots")

    build_parser = subparsers.add_parser("build", help="Build archive files from snapshots")
    build_parser.add_argument("--prune", action="store_true", help="Remove archive files not in snapshots")

    diff_parser = subparsers.add_parser("diff", help="Show local archive changes")
    diff_parser.add_argument("--issue", help="Issue number to inspect")

    push_parser = subparsers.add_parser("push", help="Push local archive changes to Buttondown")
    push_parser.add_argument("--issue", help="Issue number to push")
    push_parser.add_argument("--dry-run", action="store_true", help="Preview changes without PATCHing")
    push_parser.add_argument("--yes", action="store_true", help="Actually PATCH Buttondown")
    push_parser.add_argument("--force", action="store_true", help="Push local changes even if remote changed")

    args = parser.parse_args()
    if args.command == "pull" and args.all:
        pull_all(args)
    elif args.command == "pull" and args.latest:
        pull_latest(args)
    elif args.command == "build":
        cmd_build(args)
    elif args.command == "diff":
        cmd_diff(args)
    elif args.command == "push":
        push(args)


if __name__ == "__main__":
    main()
