"""Build a citation-ready corpus for the archive librarian."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
from pathlib import Path
from typing import Any

import httpx
import yaml
from dotenv import load_dotenv


REPO = Path(__file__).resolve().parents[1]
ARCHIVE_DIR = REPO / "src" / "archive"
OUT_PATH = REPO / "data" / "librarian" / "corpus.json"
OPENAI_EMBEDDINGS_URL = "https://api.openai.com/v1/embeddings"
DEFAULT_EMBEDDING_MODEL = "text-embedding-3-small"
DEFAULT_EMBEDDING_DIMENSIONS = 256
GENERATED_NOTICE_RE = re.compile(r"^<!-- Generated by scripts/content\.py.*?-->\s*", re.S)
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?", re.S)
TEMPLATE_LEAK_RE = re.compile(r"({%\s*|{{\s*|buttondown-editor-mode|Generated by scripts/content\.py)", re.I)
HEADING_RE = re.compile(r"^(#{1,4})\s+(.+?)\s*$", re.M)
WORD_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9'\-]*")


def issue_sort_key(value: Any) -> tuple[int, str]:
    text = str(value)
    match = re.match(r"(\d+)", text)
    if not match:
        return (10**9, text)
    return (int(match.group(1)), text)


def read_issue(path: Path) -> tuple[dict[str, Any], str]:
    text = path.read_text(encoding="utf-8")
    text = GENERATED_NOTICE_RE.sub("", text)
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise RuntimeError(f"{path} is missing YAML front matter")
    metadata = yaml.safe_load(match.group(1)) or {}
    body = GENERATED_NOTICE_RE.sub("", text[match.end() :]).strip()
    return metadata, body


def clean_heading(value: str) -> str:
    value = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", value)
    value = re.sub(r"[*_`#]+", "", value)
    return " ".join(value.split())


def split_sections(body: str) -> list[tuple[str, str]]:
    matches = list(HEADING_RE.finditer(body))
    if not matches:
        return [("Issue", body.strip())]

    sections: list[tuple[str, str]] = []
    if matches[0].start() > 0:
        intro = body[: matches[0].start()].strip()
        if intro:
            sections.append(("Issue", intro))

    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(body)
        section_body = body[start:end].strip()
        if section_body:
            sections.append((clean_heading(match.group(2)), section_body))
    return sections


def words(text: str) -> list[str]:
    return WORD_RE.findall(text)


def chunk_section(text: str, max_words: int = 260, overlap_words: int = 40) -> list[str]:
    tokens = words(text)
    if len(tokens) <= max_words:
        return [text.strip()] if text.strip() else []

    paragraphs = [p.strip() for p in re.split(r"\n{2,}", text) if p.strip()]
    chunks: list[str] = []
    current: list[str] = []
    current_words = 0

    for paragraph in paragraphs:
        count = len(words(paragraph))
        if current and current_words + count > max_words:
            chunks.append("\n\n".join(current).strip())
            overlap = " ".join(words(chunks[-1])[-overlap_words:])
            current = [overlap, paragraph] if overlap else [paragraph]
            current_words = len(words(overlap)) + count
        else:
            current.append(paragraph)
            current_words += count

    if current:
        chunks.append("\n\n".join(current).strip())
    return chunks


def chunk_id(issue_number: Any, section: str, index: int, text: str) -> str:
    digest = hashlib.sha256(f"{issue_number}\0{section}\0{index}\0{text}".encode("utf-8")).hexdigest()
    return digest[:16]


def build_corpus(archive_dir: Path = ARCHIVE_DIR) -> dict[str, Any]:
    chunks: list[dict[str, Any]] = []
    issues = []
    for path in sorted(archive_dir.glob("*.md"), key=lambda p: issue_sort_key(p.stem)):
        metadata, body = read_issue(path)
        number = metadata.get("number") or path.stem
        subject = metadata.get("subject") or f"Weekly Thing {number}"
        publish_date = metadata.get("publish_date") or ""
        url = f"/archive/{number}/"
        issue_word_count = len(words(body))
        issues.append(
            {
                "number": number,
                "subject": subject,
                "publish_date": publish_date,
                "url": url,
                "word_count": issue_word_count,
            }
        )

        for section, section_body in split_sections(body):
            for index, chunk_text in enumerate(chunk_section(section_body)):
                if TEMPLATE_LEAK_RE.search(chunk_text):
                    raise RuntimeError(f"Template/generated content leaked into corpus for issue {number}")
                chunks.append(
                    {
                        "id": chunk_id(number, section, index, chunk_text),
                        "issue_number": number,
                        "subject": subject,
                        "publish_date": publish_date,
                        "url": url,
                        "section": section,
                        "text": chunk_text,
                        "word_count": len(words(chunk_text)),
                    }
                )

    return {
        "version": 1,
        "source": "src/archive",
        "embedding_model": None,
        "issue_count": len(issues),
        "chunk_count": len(chunks),
        "issues": issues,
        "chunks": chunks,
    }


def fetch_embeddings(inputs: list[str], model: str, api_key: str, dimensions: int) -> list[list[float]]:
    response = httpx.post(
        OPENAI_EMBEDDINGS_URL,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json={"model": model, "input": inputs, "encoding_format": "float", "dimensions": dimensions},
        timeout=60,
    )
    response.raise_for_status()
    data = response.json()["data"]
    return [item["embedding"] for item in sorted(data, key=lambda item: item["index"])]


def add_openai_embeddings(corpus: dict[str, Any], model: str, dimensions: int, batch_size: int = 96) -> None:
    load_dotenv()
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is required to build embeddings")

    chunks = corpus["chunks"]
    for start in range(0, len(chunks), batch_size):
        batch = chunks[start : start + batch_size]
        inputs = [
            "\n".join(
                [
                    f"Weekly Thing #{chunk['issue_number']}: {chunk['subject']}",
                    f"Section: {chunk['section']}",
                    chunk["text"],
                ]
            )
            for chunk in batch
        ]
        embeddings = fetch_embeddings(inputs, model, api_key, dimensions)
        for chunk, embedding in zip(batch, embeddings):
            chunk["embedding"] = embedding
        print(f"Embedded chunks {start + 1}-{start + len(batch)} of {len(chunks)}")
    corpus["embedding_model"] = model
    corpus["embedding_dimensions"] = len(chunks[0]["embedding"]) if chunks else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(OUT_PATH), help="Output JSON path")
    parser.add_argument("--embed", action="store_true", help="Add OpenAI embeddings to each chunk")
    parser.add_argument("--embedding-model", default=DEFAULT_EMBEDDING_MODEL)
    parser.add_argument("--embedding-dimensions", type=int, default=DEFAULT_EMBEDDING_DIMENSIONS)
    args = parser.parse_args()

    corpus = build_corpus()
    if args.embed:
        add_openai_embeddings(corpus, args.embedding_model, args.embedding_dimensions)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(corpus, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {corpus['chunk_count']} chunks from {corpus['issue_count']} issues to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
